// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BodySize } from "./BodySize";
import type { CasteTag } from "./CasteTag";
import type { Gait } from "./Gait";
import type { Milkable } from "./Milkable";
import type { Name } from "./Name";
import type { SingPlurName } from "./SingPlurName";
import type { Tile } from "./Tile";

export type Caste = {
  identifier: string;
  tags: Array<CasteTag> | null;
  description: string | null;
  babyName: SingPlurName | null;
  casteName: Name | null;
  childName: SingPlurName | null;
  /**
   * Default \[0,0\]
   */
  clutchSize: [number, number] | null;
  /**
   * Default \[0,0\]
   */
  litterSize: [number, number] | null;
  /**
   * Default \[0,0\]
   */
  maxAge: [number, number] | null;
  baby: number | null;
  child: number | null;
  difficulty: number | null;
  eggSize: number | null;
  grassTrample: number | null;
  grazer: number | null;
  lowLightVision: number | null;
  petValue: number | null;
  popRatio: number | null;
  changeBodySizePercentage: number | null;
  creatureClass: Array<string> | null;
  bodySize: Array<BodySize> | null;
  milkable: Milkable | null;
  tile: Tile | null;
  /**
   * The gaits by which the creature can move.
   */
  gaits: Array<Gait> | null;
};
