// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::creature_caste::Caste

export type Caste = {
  identifier: string;
  tags: CasteTag[] | null;
  description: string | null;
  babyName: SingPlurName | null;
  casteName: Name | null;
  childName: SingPlurName | null;
  clutchSize: number[] | null;
  litterSize: number[] | null;
  maxAge: number[] | null;
  baby: number | null;
  child: number | null;
  difficulty: number | null;
  eggSize: number | null;
  grassTrample: number | null;
  grazer: number | null;
  lowLightVision: number | null;
  petValue: number | null;
  popRatio: number | null;
  changeBodySizePercentage: number | null;
  creatureClass: string[] | null;
  bodySize: BodySize[] | null;
  milkable: Milkable | null;
  tile: Tile | null;
  gaits: Gait[] | null;
};
