// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatureEffectProperty } from "./CreatureEffectProperty";

export type CreatureEffect = {
  severity: number;
  probability: number;
  affectedBodyPartsByCategory: Array<string> | null;
  affectedBodyPartsByType: Array<string> | null;
  affectedBodyPartsByToken: Array<string> | null;
  tags: Array<CreatureEffectProperty> | null;
  start: number;
  peak: number;
  end: number;
  dwfStretch: number | null;
};
