// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatureTag =
  | {
      AltTile: {
        /**
         * The character or tile number
         */
        character: number;
      };
    }
  | {
      ApplyCreatureVariation: {
        /**
         * Creature variation ID to apply
         */
        id: string;
        /**
         * (Optional) any number of arguments to pass to the creature variation
         */
        args: Array<string>;
      };
    }
  | "ApplyCurrentCreatureVariation"
  | "ArtificialHiveable"
  | {
      Biome: {
        /**
         * Biome identifier
         */
        id: string;
      };
    }
  | {
      Caste: {
        /**
         * The name of the caste
         */
        name: string;
      };
    }
  | {
      ChangeFrequencyPercent: {
        /**
         * The percentage to change the frequency by
         */
        percent: number;
      };
    }
  | {
      ClusterNumber: {
        /**
         * The minimum number of creatures per spawned cluster
         */
        min: number;
        /**
         * The maximum number of creatures per spawned cluster
         */
        max: number;
      };
    }
  | {
      CopyTagsFrom: {
        /**
         * The identifier of the creature to copy
         */
        creature: string;
      };
    }
  | {
      CreatureSoldierTile: {
        /**
         * The character or tile number
         */
        character: number;
      };
    }
  | {
      CreatureTile: {
        /**
         * The character or tile number
         */
        character: number;
      };
    }
  | {
      Color: {
        /**
         * The foreground color
         */
        foreground: number;
        /**
         * The background color
         */
        background: number;
        /**
         * The brightness of the color
         */
        brightness: number;
      };
    }
  | "DoesNotExist"
  | "EquipmentWagon"
  | "Evil"
  | "Fanciful"
  | {
      Frequency: {
        /**
         * The frequency of the creature, a number between 0 and 100 (inclusive)
         */
        frequency: number;
      };
    }
  | {
      GeneralBabyName: {
        /**
         * The name of the baby
         */
        singular: string;
        /**
         * The plural name of the baby
         */
        plural: string;
      };
    }
  | {
      GeneralChildName: {
        /**
         * The name of the child
         */
        singular: string;
        /**
         * The plural name of the child
         */
        plural: string;
      };
    }
  | "Generated"
  | {
      GlowColor: {
        /**
         * The foreground color
         */
        foreground: number;
        /**
         * The background color
         */
        background: number;
        /**
         * The brightness of the color
         */
        brightness: number;
      };
    }
  | {
      GlowTile: {
        /**
         * The character or tile number
         */
        character: number;
      };
    }
  | "Good"
  | "GoToEnd"
  | "GoToStart"
  | {
      GoToTag: {
        /**
         * The tag to insert after
         */
        tag: string;
      };
    }
  | {
      HarvestProduct: {
        /**
         * The number of products harvested
         */
        number: number;
        /**
         * The time it takes before the next harvest
         */
        time: number;
        /**
         * The item tokens that are harvested (some arbitrary list of items)
         */
        item_tokens: Array<string>;
      };
    }
  | "LargeRoaming"
  | "LocalPopsControllable"
  | "LocalPopsProduceHeroes"
  | "LooseClusters"
  | "Mundane"
  | {
      Name: {
        /**
         * The name of the creature
         */
        name: string;
        /**
         * The plural name of the creature
         */
        plural_name: string;
        /**
         * The adjective form of the creature's name
         */
        adjective: string;
      };
    }
  | {
      PlusMaterial: {
        /**
         * The material to add
         */
        material: string;
      };
    }
  | {
      PopulationNumber: {
        /**
         * The minimum number of creatures per spawned cluster
         */
        min: number;
        /**
         * The maximum number of creatures per spawned cluster
         */
        max: number;
      };
    }
  | {
      PrefString: {
        /**
         * The preference string
         */
        pref_string: string;
      };
    }
  | {
      ProfessionName: {
        /**
         * The profession id
         */
        id: string;
        /**
         * The name of the profession
         */
        name: string;
        /**
         * The plural name of the profession
         */
        plural_name: string;
      };
    }
  | {
      RemoveMaterial: {
        /**
         * The material to remove
         */
        material: string;
      };
    }
  | {
      RemoveTissue: {
        /**
         * The tissue to remove
         */
        tissue: string;
      };
    }
  | "Savage"
  | {
      SelectAdditionalCaste: {
        /**
         * The caste to add
         */
        caste: string;
      };
    }
  | {
      SelectCaste: {
        /**
         * The caste to select
         */
        caste: string;
      };
    }
  | {
      SelectMaterial: {
        /**
         * The material to select
         */
        material: string;
      };
    }
  | {
      SelectTissue: {
        /**
         * The tissue to select
         */
        tissue: string;
      };
    }
  | {
      SlainSpeech: {
        /**
         * The speech set to use
         */
        slain_speech: string;
      };
    }
  | {
      SmellTrigger: {
        /**
         * The smell trigger
         */
        smell_trigger: number;
      };
    }
  | {
      SoldierAltTile: {
        /**
         * The tile to use
         */
        tile: string;
      };
    }
  | {
      SourceHfid: {
        /**
         * The historical figure ID
         */
        hfid: number;
      };
    }
  | {
      Sphere: {
        /**
         * The sphere to use
         */
        sphere: string;
      };
    }
  | {
      Tissue: {
        /**
         * The name of the tissue
         */
        name: string;
      };
    }
  | {
      TriggerableGroup: {
        /**
         * The minimum number of vermin in the swarm
         */
        min: number;
        /**
         * The maximum number of vermin in the swarm
         */
        max: number;
      };
    }
  | "Ubiquitous"
  | {
      UndergroundDepth: {
        /**
         * The minimum depth
         */
        min: number;
        /**
         * The maximum depth
         */
        max: number;
      };
    }
  | {
      UseCaste: {
        /**
         * The name of the new caste
         */
        caste: string;
        /**
         * The name of the original caste to copy
         */
        original_caste: string;
      };
    }
  | {
      UseMaterial: {
        /**
         * The name of the new material
         */
        material: string;
        /**
         * The name of the original material to copy
         */
        original_material: string;
      };
    }
  | {
      UseMaterialTemplate: {
        /**
         * The name of the new material
         */
        material: string;
        /**
         * The name of the template to copy
         */
        template: string;
      };
    }
  | {
      UseTissue: {
        /**
         * The name of the new tissue
         */
        tissue: string;
        /**
         * The name of the original tissue to copy
         */
        original_tissue: string;
      };
    }
  | {
      UseTissueTemplate: {
        /**
         * The name of the new tissue
         */
        tissue: string;
        /**
         * The name of the template to copy
         */
        template: string;
      };
    }
  | "Utterances"
  | "VerminEater"
  | "VerminFish"
  | "VerminGrounder"
  | "VerminRotter"
  | "VerminSoil"
  | "VerminSoilColony"
  | "Unknown"
  | "MatesToBreed"
  | "TwoGenders"
  | "AllCastesAlive"
  | "SmallRace"
  | "OccursAsEntityRace"
  | "Equipment";
