// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::creature_variation::Token

export type CVTag =
  | "NewTag"
  | "AddTag"
  | "RemoveTag"
  | "ConvertTag"
  | "ConvertTagMaster"
  | "ConvertTagTarget"
  | "ConvertTagReplacement"
  | "ConditionalNewTag"
  | "ConditionalAddTag"
  | "ConditionalRemoveTag"
  | "ConditionalConvertTag"
  | "Unknown";
