// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::creature_caste::Token

/**
 * Tokens that can be found in a creature's caste definitions.
 */
export type CasteTag =
  | "AdoptsOwner"
  | "AlcoholDependent"
  | "AllActive"
  | { AltTile: { tile: string } }
  | "AmbushPredator"
  | "Amphibious"
  | { ApplyCreatureVariation: { id: string; args: string[] } }
  | "ApplyCurrentCreatureVariation"
  | "Aquatic"
  | "ArenaRestricted"
  | "AtPeaceWithWildlife"
  | { Attack: { name: string; body_part: string } }
  | {
      AttackTrigger: {
        population: number;
        exported_wealth: number;
        created_wealth: number;
      };
    }
  | { Baby: { age: number } }
  | { BabyName: { singular: string; plural: string } }
  | { BeachFrequency: { frequency: number } }
  | "Benign"
  | { Blood: { material: string; state: string } }
  | "BloodSucker"
  | { Body: { body_parts: string[] } }
  | { BodyAppearanceModifier: { attribute: string; values: number[] } }
  | { BodyDetailPlan: { body_plan: string; arguments: string[] } }
  | { BodySize: { year: number; days: number; size: number } }
  | { BodyGloss: { gloss: string } }
  | "BoneCarn"
  | { BodyPartAddType: { body_part_type: string } }
  | { BodyPartAppearanceModifier: { quality: string; spread: number[] } }
  | { BodyPartRemoveType: { body_part_type: string } }
  | { BuildingDestroyer: { door_and_furniture_focused: boolean } }
  | { CanDoInteraction: { interaction: string } }
  | "CanLearn"
  | "CanSpeak"
  | "CannotClimb"
  | "CannotJump"
  | "CannotUndead"
  | "CanOpenDoors"
  | "Carnivore"
  | "CaveAdaptation"
  | { ChangeBodySizePercent: { percent: number } }
  | { Child: { age: number } }
  | { ChildName: { singular: string; plural: string } }
  | { ClutchSize: { min: number; max: number } }
  | { Color: { foreground: number; background: number; brightness: number } }
  | "CommonDomestic"
  | "ConvertedSpouse"
  | "CookableLive"
  | "Crazed"
  | { CreatureClass: { class: string } }
  | "Crepuscular"
  | "CuriousBeastEater"
  | "CuriousBeastGuzzler"
  | "CuriousBeastItem"
  | { CreatureVariationAddTag: { tag: string } }
  | { CreatureVariationRemoveTag: { tag: string } }
  | "Demon"
  | { Description: { description: string } }
  | "DieWhenVerminBite"
  | { Difficulty: { difficulty: number } }
  | "Diurnal"
  | "DiveHuntsVermin"
  | { ExtraButcherObjectItem: { item: string; material: string } }
  | { ExtraButcherObjectShape: { shape: string } }
  | { EggMaterial: { material: string; state: string } }
  | { EggSize: { size: number } }
  | "Equips"
  | { ExtraButcherObject: { object_type: string; arguments: string[] } }
  | { Extract: { material: string } }
  | "Extravision"
  | "FeatureAttackGroup"
  | "FeatureBeast"
  | "Female"
  | "FireImmune"
  | "FireImmuneSuper"
  | "FishItem"
  | { FixedTemp: { temperature: number } }
  | "FleeQuick"
  | "Flier"
  | { Gait: { gait: string } }
  | { GeneralMaterialForceMultiplier: { value_a: number; value_b: number } }
  | "GetsInfectionsFromRot"
  | "GetsWoundInfections"
  | {
      GlowColor: { foreground: number; background: number; brightness: number };
    }
  | { GlowTile: { tile: string } }
  | { Gnawer: { verb: string } }
  | { GobbleVerminClass: { vermin_class: string } }
  | { GobbleVerminCreature: { vermin_creature: string; vermin_caste: string } }
  | { GrassTrample: { trample: number } }
  | { GravitateBodySize: { target: number } }
  | { Grazer: { grazer: number } }
  | { Habit: { habit: string } }
  | { HabitNumber: { number: number } }
  | "HasNerves"
  | "HasShell"
  | { Homeotherm: { temperature: number | null } }
  | "HuntsVermin"
  | "Immobile"
  | "ImmobileLand"
  | "Immolate"
  | "Intelligent"
  | { InteractionDetail: { args: string[] } }
  | { ItemCorpse: { item: string; material: string } }
  | { ItemCorpseQuality: { quality: number } }
  | { Lair: { lair: string; probability: number } }
  | { LairCharacteristic: { characteristic: string } }
  | "LairHunter"
  | { LairHunterSpeech: { speech_file: string } }
  | "LargePredator"
  | "LaysEggs"
  | { LaysUnusualEggs: { item: string; material: string } }
  | { Ligaments: { material: string; healing_rate: number } }
  | "LightGen"
  | "LikesFighting"
  | "Lisp"
  | { LitterSize: { min: number; max: number } }
  | "LockPicker"
  | { LowLightVision: { vision: number } }
  | "Magical"
  | "MagmaVision"
  | "Male"
  | "MannerismLaugh"
  | "MannerismSmile"
  | "MannerismWalk"
  | "MannerismSit"
  | "MannerismBreath"
  | "MannerismPosture"
  | "MannerismStretch"
  | "MannerismEyelids"
  | { MannerismFingers: { finger: string; fingers: string } }
  | { MannerismNose: { nose: string } }
  | { MannerismEar: { ear: string } }
  | { MannerismHead: { head: string } }
  | { MannerismEyes: { eyes: string } }
  | { MannerismMouth: { mouth: string } }
  | { MannerismHair: { hair: string } }
  | { MannerismKnuckles: { knuckles: string } }
  | { MannerismLips: { lips: string } }
  | { MannerismCheek: { cheek: string } }
  | { MannerismNails: { nails: string } }
  | { MannerismFeet: { feet: string } }
  | { MannerismArms: { arms: string } }
  | { MannerismHands: { hands: string } }
  | { MannerismTongue: { tongue: string } }
  | { MannerismLeg: { leg: string } }
  | "Matutinal"
  | { MaxAge: { min: number; max: number } }
  | "Meanderer"
  | "Megabeast"
  | { MentalAttributeCapPercentage: { attribute: string; percentage: number } }
  | { MentalAttributeRange: { attribute: string; ranges: number[] } }
  | {
      MentalAttributeRate: {
        attribute: string;
        improvement_cost: number;
        decay_rate_unused: number;
        decay_rate_rusty: number;
        decay_rate_demotion: number;
      };
    }
  | { Milkable: { material: string; frequency: number } }
  | "Mischievous"
  | { ModValue: { value: string } }
  | "Mount"
  | "MountExotic"
  | "MultipartFullVision"
  | "MultipleLitterRare"
  | { Name: { singular: string; plural: string; adjective: string } }
  | "Natural"
  | { NaturalSkill: { skill: string; level: number } }
  | "NightCreatureBogeyman"
  | "NightCreatureExperimenter"
  | "NightCreatureHunter"
  | "NightCreatureNightmare"
  | "NoConnectionsForMovement"
  | "NoDizziness"
  | "NoDrink"
  | "NoEat"
  | "NoFall"
  | "NoFevers"
  | "NoGender"
  | "NoPhysicalAttributeGain"
  | "NoPhysicalAttributeRust"
  | "NoSleep"
  | "NoSpring"
  | "NoSummer"
  | "NoThoughtCenterForMovement"
  | "NoUnitTypeColor"
  | "NoVegetationDisturbance"
  | "NoWinter"
  | "NoBones"
  | "NoBreathe"
  | "Nocturnal"
  | "NoEmotion"
  | "NoExert"
  | "NoFear"
  | "NoMeat"
  | "NoNausea"
  | "NoPain"
  | "NoSkin"
  | "NoSkull"
  | "NoSmellyRot"
  | "NoStuckIns"
  | "NoStun"
  | "NotButcherable"
  | "NotLiving"
  | "NoThought"
  | { OdorLevel: { odor_level: number } }
  | { OdorString: { odor_string: string } }
  | "OpposedToLife"
  | {
      Orientation: {
        caste: string;
        disinterested_chance: number;
        casual_chance: number;
        strong_chance: number;
      };
    }
  | "OutsiderControllable"
  | "PackAnimal"
  | "ParalyzeImmune"
  | "PatternFlier"
  | "Pearl"
  | { PenetratePower: { penetrate_power: number } }
  | {
      Personality: {
        personality_trait: string;
        low: number;
        median: number;
        high: number;
      };
    }
  | "Pet"
  | "PetExotic"
  | { PetValue: { pet_value: number } }
  | { PetValueDivisor: { divisor: number } }
  | {
      PhysicalAttributeCapPercentage: { attribute: string; percentage: number };
    }
  | { PhysicalAttributeRange: { attribute: string; ranges: number[] } }
  | {
      PhysicalAttributeRate: {
        attribute: string;
        improvement_cost: number;
        decay_rate_unused: number;
        decay_rate_rusty: number;
        decay_rate_demotion: number;
      };
    }
  | {
      PlusBodyPartGroup: {
        body_part_selector: string;
        body_part_group: string;
      };
    }
  | { PopulationRatio: { pop_ratio: number } }
  | "Power"
  | { ProfessionName: { profession: string; singular: string; plural: string } }
  | { ProneToRage: { rage_chance: number } }
  | { Pus: { material: string; material_state: string } }
  | {
      RelativeSize: {
        body_part_selector: string;
        body_part: string;
        relative_size: number;
      };
    }
  | { Remains: { singular: string; plural: string } }
  | { RemainsColor: { remains_color: string } }
  | "RemainsOnVerminBiteDeath"
  | "RemainsUndetermined"
  | {
      RetractIntoBodyPart: {
        body_part_selector: string;
        body_part: string;
        second_person: string;
        third_person: string;
        second_person_cancel: string;
        third_person_cancel: string;
      };
    }
  | "ReturnsVerminKillsToOwner"
  | {
      RootAround: {
        body_part_selector: string;
        body_part: string;
        second_person_verb: string;
        third_person_verb: string;
      };
    }
  | {
      Secretion: {
        material_token: string;
        material_state: string;
        body_part_selector: string;
        body_part: string;
        tissue_layer: string;
        trigger: string;
      };
    }
  | "SemiMegabeast"
  | {
      SenseCreatureClass: {
        creature_class: string;
        tile: string;
        foreground: number;
        background: number;
        brightness: number;
      };
    }
  | { SetBodyPartGroup: { body_part_selector: string; body_part: string } }
  | { SkillLearnRate: { skill: string; rate: number } }
  | { SkillLearnRates: { rate: number } }
  | {
      SkillRate: {
        skill: string;
        improvement_rate: number;
        decay_rate_unused: number;
        decay_rate_rusty: number;
        decay_rate_demotion: number;
      };
    }
  | {
      SkillRates: {
        improvement_rate: number;
        decay_rate_unused: number;
        decay_rate_rusty: number;
        decay_rate_demotion: number;
      };
    }
  | {
      SkillRustRate: {
        skill: string;
        decay_rate_unused: number;
        decay_rate_rusty: number;
        decay_rate_demotion: number;
      };
    }
  | {
      SkillRustRates: {
        decay_rate_unused: number;
        decay_rate_rusty: number;
        decay_rate_demotion: number;
      };
    }
  | { SlainSpeech: { speech_file: string } }
  | "SlowLearner"
  | "SmallRemains"
  | { SoldierTile: { tile: string } }
  | { SoldierAltTile: { tile: string } }
  | {
      Sound: {
        sound_type: string;
        sound_range: number;
        sound_interval: number;
        requires_breathing: boolean;
        first_person: string;
        third_person: string;
        out_of_sight: string;
      };
    }
  | { SpecificFood: { is_plant: boolean; identifier: string } }
  | "SpouseConversionTarget"
  | "SpouseConverter"
  | "SpreadEvilSpheresIfRuler"
  | "StanceClimber"
  | "StandardGrazer"
  | "StrangeMoods"
  | "Supernatural"
  | "SwimsInnate"
  | "SwimsLearned"
  | { SyndromeDilutionFactor: { syndrome: string; percentage: number } }
  | { Tendons: { material: string; healing_rate: number } }
  | "ThickWeb"
  | { Tile: { tile: string } }
  | {
      TissueLayer: {
        body_part_selector: string;
        body_part: string;
        tissue: string;
        location: string;
      };
    }
  | {
      TissueLayerUnder: {
        body_part_selector: string;
        body_part: string;
        tissue: string;
      };
    }
  | "Titan"
  | { TradeCapacity: { capacity: number } }
  | "Trainable"
  | "TrainableHunting"
  | "TrainableWar"
  | "Trances"
  | "TrapAvoid"
  | "UnderSwim"
  | "UniqueDemon"
  | "Vegetation"
  | {
      VerminBite: {
        chance: number;
        verb: string;
        material: string;
        material_state: string;
      };
    }
  | "VerminHateable"
  | "VerminMicro"
  | "VerminNoFish"
  | "VerminNoRoam"
  | "VerminNoTrap"
  | "VerminHunter"
  | "Vespertine"
  | { ViewRange: { view_range: number } }
  | { VisionArc: { binocular: number; non_binocular: number } }
  | "WagonPuller"
  | { Webber: { material: string } }
  | "WebImmune"
  | "Unknown"
  | "NightCreature"
  | "NotFireImmune"
  | "HasBlood"
  | "Grasp"
  | "RaceGait"
  | "CannotBreatheWater"
  | "NaturalAnimal"
  | "CuriousBeast"
  | "CannotBreatheAir";
