// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::creature_variation::CreatureVariation

export type CreatureVariation = {
  metadata: Metadata | null;
  identifier: string;
  objectId: string;
  rules: CreatureVariationRule[];
  argumentCount: string;
};
