// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::creature::Token

export type CreatureTag =
  | { AltTile: { character: number } }
  | { ApplyCreatureVariation: { id: string; args: string[] } }
  | "ApplyCurrentCreatureVariation"
  | "ArtificialHiveable"
  | { Biome: { id: string } }
  | { Caste: { name: string } }
  | { ChangeFrequencyPercent: { percent: number } }
  | { ClusterNumber: { min: number; max: number } }
  | { CopyTagsFrom: { creature: string } }
  | { CreatureSoldierTile: { character: number } }
  | { CreatureTile: { character: number } }
  | { Color: { foreground: number; background: number; brightness: number } }
  | "DoesNotExist"
  | "EquipmentWagon"
  | "Evil"
  | "Fanciful"
  | { Frequency: { frequency: number } }
  | { GeneralBabyName: { singular: string; plural: string } }
  | { GeneralChildName: { singular: string; plural: string } }
  | "Generated"
  | {
      GlowColor: { foreground: number; background: number; brightness: number };
    }
  | { GlowTile: { character: number } }
  | "Good"
  | "GoToEnd"
  | "GoToStart"
  | { GoToTag: { tag: string } }
  | { HarvestProduct: { number: number; time: number; item_tokens: string[] } }
  | "LargeRoaming"
  | "LocalPopsControllable"
  | "LocalPopsProduceHeroes"
  | "LooseClusters"
  | "Mundane"
  | { Name: { name: string; plural_name: string; adjective: string } }
  | { PlusMaterial: { material: string } }
  | { PopulationNumber: { min: number; max: number } }
  | { PrefString: { pref_string: string } }
  | { ProfessionName: { id: string; name: string; plural_name: string } }
  | { RemoveMaterial: { material: string } }
  | { RemoveTissue: { tissue: string } }
  | "Savage"
  | { SelectAdditionalCaste: { caste: string } }
  | { SelectCaste: { caste: string } }
  | { SelectMaterial: { material: string } }
  | { SelectTissue: { tissue: string } }
  | { SlainSpeech: { slain_speech: string } }
  | { SmellTrigger: { smell_trigger: number } }
  | { SoldierAltTile: { tile: string } }
  | { SourceHfid: { hfid: number } }
  | { Sphere: { sphere: string } }
  | { Tissue: { name: string } }
  | { TriggerableGroup: { min: number; max: number } }
  | "Ubiquitous"
  | { UndergroundDepth: { min: number; max: number } }
  | { UseCaste: { caste: string; original_caste: string } }
  | { UseMaterial: { material: string; original_material: string } }
  | { UseMaterialTemplate: { material: string; template: string } }
  | { UseTissue: { tissue: string; original_tissue: string } }
  | { UseTissueTemplate: { tissue: string; template: string } }
  | "Utterances"
  | "VerminEater"
  | "VerminFish"
  | "VerminGrounder"
  | "VerminRotter"
  | "VerminSoil"
  | "VerminSoilColony"
  | "Unknown"
  | "MatesToBreed"
  | "TwoGenders"
  | "AllCastesAlive"
  | "SmallRace"
  | "OccursAsEntityRace"
  | "Equipment";
