// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::parser::graphics::CustomGraphicExtension

export type CustomGraphicExtension = {
  extensionType: GraphicType;
  tilePageId: string | null;
  value1: number | null;
  value2: number | null;
};
