// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphicType } from "./GraphicType";

export type CustomGraphicExtension = {
  extensionType: GraphicType;
  tilePageId: string | null;
  value1: number | null;
  value2: number | null;
};
