// File generated by specta. Do not edit!
//
/// lib/tauri_lib library

/**
 * Details about the current file being parsed, specifically where and what it is.
 */
export type ProgressDetails = {
  location: RawModuleLocation;
  module: string | null;
  rawFile: string | null;
  fileLocation: string | null;
};

/**
 * Tasks that describe what the parser is currently doing.
 */
export type ProgressTask =
  | "parseRaws"
  | "parseLegends"
  | "parseModuleInfoFiles"
  | "resolveRaws"
  | "idle";

/**
 * A payload that can be used to gauge the progress of the parsing process.
 */
export type ProgressPayload = {
  details: ProgressDetails;
  currentTask: ProgressTask;
  percentage: number;
  runningTotal: string;
};

/**
 * Raws are part of modules since 50.xx. Raw modules are loaded from 3 common locations:
 * `{df_directory}/data/vanilla`, `{df_directory}/mods`, and `{df_directory/data/installed_mods}`
 */
export type RawModuleLocation =
  | "InstalledMods"
  | "Mods"
  | "Vanilla"
  | "Unknown"
  | "LegendsExport";
