// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::inorganic::EnvironmentClassToken

export type EnvironmentClass =
  | "AllStone"
  | "IgneousAll"
  | "IgneousExtrusive"
  | "IgneousIntrusive"
  | "Soil"
  | "SoilSand"
  | "SoilOcean"
  | "Sedimentary"
  | "Metamorphic"
  | "Alluvial"
  | "None";
