// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::creature_caste::GaitType

export type GaitType =
  | "walk"
  | "crawl"
  | "climb"
  | "swim"
  | "fly"
  | { other: string }
  | "unknown";
