// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::graphics::Graphic

export type Graphic = {
  metadata: Metadata | null;
  identifier: string;
  objectId: string;
  casteIdentifier: string | null;
  kind: GraphicType;
  sprites: SpriteGraphic[] | null;
  layers: [string, SpriteLayer[]][] | null;
  growths: [string, SpriteGraphic[]][] | null;
  customExtensions: CustomGraphicExtension[] | null;
  tags: string[] | null;
};
