// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::graphics::GrowthToken

export type GrowthToken =
  | "fruit"
  | "growth1"
  | "growth2"
  | "growth3"
  | "growth4"
  | "asIs";
