// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::inorganic::InclusionTypeToken

export type InclusionType =
  | "Cluster"
  | "ClusterSmall"
  | "ClusterOne"
  | "Vein"
  | "None";
