// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentClass } from "./EnvironmentClass";
import type { InclusionType } from "./InclusionType";
import type { InorganicToken } from "./InorganicToken";
import type { Material } from "./Material";
import type { RawMetadata } from "./RawMetadata";

export type Inorganic = {
  identifier: string;
  metadata: RawMetadata | null;
  objectId: string;
  material: Material;
  metalOreChance: Array<[string, number]> | null;
  threadMetalChance: Array<[string, number]> | null;
  environmentClass: EnvironmentClass | null;
  environmentInclusionType: InclusionType | null;
  environmentInclusionFrequency: number | null;
  environmentClassSpecific: Array<string> | null;
  tags: Array<InorganicToken> | null;
};
