// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::inorganic::Inorganic

export type Inorganic = {
  identifier: string;
  metadata: Metadata | null;
  objectId: string;
  material: Material;
  metalOreChance: [string, number][] | null;
  threadMetalChance: [string, number][] | null;
  environmentClass: EnvironmentClass | null;
  environmentInclusionType: InclusionType | null;
  environmentInclusionFrequency: number | null;
  environmentClassSpecific: string[] | null;
  tags: InorganicToken[] | null;
};
