// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::inorganic::Token

export type InorganicToken =
  | "Wafers"
  | "DeepSpecial"
  | "MetalOre"
  | "ThreadMetal"
  | "DeepSurface"
  | "Aquifer"
  | "Metamorphic"
  | "Sedimentary"
  | "Soil"
  | "SoilOcean"
  | "SoilSand"
  | "SedimentaryOceanShallow"
  | "SedimentaryOceanDeep"
  | "IgneousExtrusive"
  | "IgneousIntrusive"
  | "Environment"
  | "EnvironmentSpecific"
  | "Lava"
  | "Special"
  | "Generated"
  | "Divine"
  | "Sphere"
  | "Unknown";
