// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MechanicalProperties } from "./MechanicalProperties";

/**
 * Represents the specific yield, fracture, and elasticity of a material for the various
 * types of mechanical stress.
 */
export type MaterialMechanics = {
  impact: MechanicalProperties | null;
  compressive: MechanicalProperties | null;
  tensile: MechanicalProperties | null;
  torsion: MechanicalProperties | null;
  shear: MechanicalProperties | null;
  bending: MechanicalProperties | null;
  maxEdge: number | null;
  solidDensity: number | null;
};
