// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::material::Material

export type Material = {
  materialType: MaterialType | null;
  name: string | null;
  fuelType: FuelType | null;
  creatureIdentifier: string | null;
  plantIdentifier: string | null;
  isLocalMaterial: boolean | null;
  reagentIdentifier: string | null;
  reactionProductIdentifier: string | null;
  templateIdentifier: string | null;
  usage: MaterialUsage[] | null;
  value: number | null;
  color: Color | null;
  stateNames: StateName | null;
  stateAdjectives: StateName | null;
  stateColors: StateName | null;
  temperatures: Temperatures | null;
  properties: string[] | null;
  syndromes: Syndrome[] | null;
  mechanicalProperties: MaterialMechanics | null;
  liquidDensity: number | null;
  molarMass: number | null;
  buildColor: Color | null;
  displayColor: Color | null;
  tile: Tile | null;
  itemSymbol: string | null;
};
