// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::material_template::MaterialTemplate

export type MaterialTemplate = {
  identifier: string;
  metadata: Metadata | null;
  objectId: string;
  material: Material;
};
