// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Material } from "./Material";
import type { RawMetadata } from "./RawMetadata";

export type MaterialTemplate = {
  identifier: string;
  metadata: RawMetadata | null;
  objectId: string;
  material: Material;
};
