// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::parser::MaterialMechanics

/**
 * Represents the specific yield, fracture, and elasticity of a material for the various
 * types of mechanical stress.
 */
export type MaterialMechanics = {
  impact: MechanicalProperties | null;
  compressive: MechanicalProperties | null;
  tensile: MechanicalProperties | null;
  torsion: MechanicalProperties | null;
  shear: MechanicalProperties | null;
  bending: MechanicalProperties | null;
  maxEdge: number | null;
  solidDensity: number | null;
};
