// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::parser::MechanicalProperties

/**
 * Represents the mechanical properties of a material via the yield, fracture, and elasticity
 */
export type MechanicalProperties = {
  yield: number;
  fracture: number;
  elasticity: number;
};
