// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the mechanical properties of a material via the yield, fracture, and elasticity
 */
export type MechanicalProperties = {
  yield: number;
  fracture: number;
  elasticity: number;
};
