// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How often a creature can be milked and what material it produces
 */
export type Milkable = { material: string; frequency: number };
