// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::parser::Milkable

/**
 * How often a creature can be milked and what material it produces
 */
export type Milkable = { material: string; frequency: number };
