// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Modifier =
  | "layersSlow"
  | "strength"
  | "agility"
  | {
      stealthSlows: {
        /**
         * The percentage slowed
         */
        percentage: number;
      };
    }
  | "noBuildUp"
  | {
      buildUp: {
        /**
         * The build up time indicates how long it will take for a creature using this gait to go from `<start speed>` to `<max speed>`.
         * For example, a value of 10 means that it should be able to reach the maximum speed by moving 10 tiles in a straight line over even terrain.
         */
        time: number;
        /**
         * The turning max indicates the maximum speed permissible when the creature suddenly changes its direction of motion.
         * The creature's speed will be reduced to `<max turning speed>` if traveling at a higher speed than this before turning.
         */
        turning_max: number;
        /**
         * The creature's speed when it starts moving using this gait
         */
        start_speed: number;
      };
    };
