// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Modification =
  | { copytagsfrom: { identifier: string } }
  | { applycreaturevariation: { identifier: string } }
  | { addtoending: { raws: Array<string> } }
  | { addtobeginning: { raws: Array<string> } }
  | { addbeforetag: { tag: string; raws: Array<string> } }
  | { mainrawbody: { raws: Array<string> } };
