// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::unprocessed_raw::Modification

export type Modification =
  | { copyTagsFrom: { identifier: string } }
  | { applyCreatureVariation: { identifier: string } }
  | { addToEnding: { raws: string[] } }
  | { addToBeginning: { raws: string[] } }
  | { addBeforeTag: { tag: string; raws: string[] } }
  | { mainRawBody: { raws: string[] } };
