// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Modification =
  | {
      copyTagsFrom: {
        /**
         * The creature to copy tags from
         */
        identifier: string;
      };
    }
  | {
      applyCreatureVariation: {
        /**
         * The creature to apply the variation from
         */
        identifier: string;
      };
    }
  | {
      addToEnding: {
        /**
         * The set of raws to add to the end of the object
         *
         * This should be the entire raw in order to apply.
         */
        raws: Array<string>;
      };
    }
  | {
      addToBeginning: {
        /**
         * The set of raws to add to the beginning of the object
         *
         * This should be the entire raw in order to apply.
         */
        raws: Array<string>;
      };
    }
  | {
      addBeforeTag: {
        /**
         * The tag to insert before
         *
         * Since we don't actually know the tag order after parsing, this will be ignored in parsing, and
         * instead will just apply the raws...
         */
        tag: string;
        /**
         * The set of raws to add before the tag
         *
         * This should be the entire raw in order to apply.
         */
        raws: Array<string>;
      };
    }
  | {
      mainRawBody: {
        /**
         * The set of raws that make up the object. This is usually defined first unless
         * its specified to be added to the end or beginning (or before a tag)
         *
         * This should be the entire raw in order to apply.
         */
        raws: Array<string>;
      };
    };
