// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Modifier =
  | "layersslow"
  | "strength"
  | "agility"
  | { stealthslows: { percentage: number } }
  | "nobuildup"
  | { buildup: { time: number; turning_max: number; start_speed: number } };
