// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RawModuleLocation } from "./RawModuleLocation";
import type { SteamData } from "./SteamData";

/**
 * Represents the `info.txt` file for a raw module
 */
export type ModuleInfoFile = {
  identifier: string;
  objectId: string;
  location: RawModuleLocation;
  parentDirectory: string;
  numericVersion: number;
  displayedVersion: string;
  earliestCompatibleNumericVersion: number;
  earliestCompatibleDisplayedVersion: string;
  author: string;
  name: string;
  description: string;
  requiresIds: Array<string> | null;
  conflictsWithIds: Array<string> | null;
  requiresIdsBefore: Array<string> | null;
  requiresIdsAfter: Array<string> | null;
  steamData: SteamData | null;
};
