// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::parser::ModuleInfoFile

/**
 * Represents the `info.txt` file for a raw module
 */
export type InfoFile = {
  identifier: string;
  objectId: string;
  location: RawModuleLocation;
  parentDirectory: string;
  numericVersion: number;
  displayedVersion: string;
  earliestCompatibleNumericVersion: number;
  earliestCompatibleDisplayedVersion: string;
  author: string;
  name: string;
  description: string;
  requiresIds: string[] | null;
  conflictsWithIds: string[] | null;
  requiresIdsBefore: string[] | null;
  requiresIdsAfter: string[] | null;
  steamData: SteamData | null;
};
