// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A name with a singular, plural, and adjective form
 */
export type Name = { singular: string; plural: string; adjective: string };
