// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::parser::Name

/**
 * A name with a singular, plural, and adjective form
 */
export type Name = { singular: string; plural: string; adjective: string };
