// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrowthTag } from "./GrowthTag";
import type { GrowthType } from "./GrowthType";
import type { PlantPart } from "./PlantPart";
import type { SingPlurName } from "./SingPlurName";

export type PlantGrowth = {
  /**
   * Plant growths are not given an identifier, since they are just supporting
   * data for the plant definition. They are defined instead by the type of growth.
   */
  growthType: GrowthType;
  /**
   * The name of the growth. This is actually defined with "GROWTH_NAME" key in the raws.
   */
  name: SingPlurName;
  /**
   * The item grown by this growth. This is actually defined with "GROWTH_ITEM" key in the raws.
   * This is a string until we make a proper item structure. Technically there are 2 arguments:
   * 1. item token, 2: material token. Generally the item type should be PLANT_GROWTH:NONE.
   */
  item: string;
  /**
   * Specifies on which part of the plant this growth grows. This is defined with "GROWTH_HOST_TILE" key.
   * This can be unused, like in the case of crops where the plant is the growth (I think?).
   */
  hostTiles: Array<PlantPart> | null;
  /**
   * Controls the height on the trunk above which the growth begins to appear.
   * The first value is the percent of the trunk height where the growth begins appearing:
   * 0 will cause it along the entire trunk (above the first tile), 100 will cause it to appear
   * at the topmost trunk tile. Can be larger than 100 to cause it to appear above the trunk.
   * The second value must be -1, but might be intended to control whether it starts height counting
   * from the bottom or top.
   */
  trunkHeightPercentage: [number, number] | null;
  /**
   * Currently has no effect.
   */
  density: number | null;
  /**
   * Specifies the appearance of the growth. This is defined with "GROWTH_PRINT" key.
   * This is a string until we make a proper print structure.
   */
  print: string | null;
  /**
   * Specifies at which part of the year the growth appears. Default is all year round.
   * Minimum: 0, Maximum: 402_200. This is defined with "GROWTH_TIMING" key.
   */
  timing: [number, number] | null;
  /**
   * Where we gather some of the growth's tags.
   */
  tags: Array<GrowthTag> | null;
};
