// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::graphics::PlantGraphicTemplateToken

export type PlantGraphicTemplate =
  | "standardLeaves"
  | "standardFruit1"
  | "standardFruit2"
  | "standardFruit3"
  | "standardFruit4"
  | "standardFlowers1"
  | "standardFlowers2"
  | "standardFlowers3"
  | "standardFlowers4";
