// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::plant::Plant

export type Plant = {
  metadata: Metadata | null;
  identifier: string;
  objectId: string;
  name: Name;
  prefStrings: string[] | null;
  tags: PlantTag[] | null;
  undergroundDepth: number[] | null;
  frequency: number | null;
  biomes: Biome[] | null;
  growths: PlantGrowth[] | null;
  treeDetails: Tree | null;
  shrubDetails: Shrub | null;
  materials: Material[] | null;
};
