// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::plant_growth::TypeToken

export type GrowthType =
  | "Leaves"
  | "Spathes"
  | "Fruit"
  | "Flowers"
  | "Nut"
  | "SeedCatkins"
  | "PollenCatkins"
  | "Cone"
  | "SeedCone"
  | "PollenCone"
  | "Feathers"
  | "Eggs"
  | "Pod"
  | "None";
