// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::plant_growth::Token

export type GrowthTag =
  | "Growth"
  | "GrowthName"
  | "GrowthItem"
  | "GrowthHostTile"
  | "GrowthTrunkHeightPercent"
  | "GrowthDensity"
  | "GrowthTiming"
  | "GrowthPrint"
  | "GrowthHasSeed"
  | "GrowthDropsOff"
  | "GrowthDropsOffNoCloud"
  | "Unknown";
