// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::plant_growth::PlantGrowth

export type PlantGrowth = {
  growthType: GrowthType;
  name: SingPlurName;
  item: string;
  hostTiles: PlantPart[] | null;
  trunkHeightPercentage: number[] | null;
  density: number | null;
  print: string | null;
  timing: number[] | null;
  tags: GrowthTag[] | null;
};
