// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::plant_growth::PlantPartToken

export type PlantPart =
  | "Twigs"
  | "Branches"
  | "BranchesAndTwigs"
  | "AllBranchesAndTwigs"
  | "HeavyBranches"
  | "HeavyBranchesAndTrunk"
  | "Trunk"
  | "Roots"
  | "Cap"
  | "Sapling"
  | "Unknown";
