// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::plant::Token

export type PlantTag =
  | "Dry"
  | "Evil"
  | "Good"
  | "Savage"
  | "Wet"
  | "UndergroundDepth"
  | "Biome"
  | "Frequency"
  | "UseMaterialTemplate"
  | "BasicMaterial"
  | "UseMaterial"
  | "Material"
  | "PrefString"
  | "AllNames"
  | "NameAdjective"
  | "NamePlural"
  | "NameSingular"
  | "Unknown";
