// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Biome } from "./Biome";
import type { Material } from "./Material";
import type { Name } from "./Name";
import type { PlantGrowth } from "./PlantGrowth";
import type { PlantTag } from "./PlantTag";
import type { RawMetadata } from "./RawMetadata";
import type { Shrub } from "./Shrub";
import type { Tree } from "./Tree";

export type Plant = {
  /**
   * Common Raw file Things
   */
  metadata: RawMetadata | null;
  identifier: string;
  objectId: string;
  name: Name;
  prefStrings: Array<string> | null;
  tags: Array<PlantTag> | null;
  /**
   * Default [0, 0] (aboveground)
   */
  undergroundDepth: [number, number] | null;
  /**
   * Default frequency is 50
   */
  frequency: number | null;
  /**
   * List of biomes this plant can grow in
   */
  biomes: Array<Biome> | null;
  /**
   * Growth Tokens define the growths of the plant (leaves, fruit, etc.)
   */
  growths: Array<PlantGrowth> | null;
  /**
   * If plant is a tree, it will have details about the tree.
   */
  treeDetails: Tree | null;
  /**
   * If plant is a shrub, it will have details about the shrub.
   */
  shrubDetails: Shrub | null;
  materials: Array<Material> | null;
};
