// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::position::Position

export type Position = {
  identifier: string;
  allowedClasses: string[] | null;
  allowedCreatures: string[] | null;
  appointedBy: string | null;
  color: Color | null;
  commander: string | null;
  demandMax: number | null;
  executionSkill: string | null;
  gender: string | null;
  landHolder: number | null;
  landName: string | null;
  mandateMax: number | null;
  name: SingPlurName | null;
  nameMale: SingPlurName | null;
  nameFemale: SingPlurName | null;
  number: number | null;
  precedence: number | null;
  rejectedClasses: string[] | null;
  rejectedCreatures: string[] | null;
  replacedBy: string | null;
  requiredBedroom: number | null;
  requiredBoxes: number | null;
  requiredCabinets: number | null;
  requiredDining: number | null;
  requiredOffice: number | null;
  requiredRacks: number | null;
  requiredStands: number | null;
  requiredTomb: number | null;
  requiresPopulation: number | null;
  responsibilities: string[] | null;
  spouse: SingPlurName | null;
  spouseFemale: SingPlurName | null;
  spouseMale: SingPlurName | null;
  squad: string | null;
  succession: string | null;
  tags: PositionToken[];
};
