// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressDetails } from "./ProgressDetails";
import type { ProgressTask } from "./ProgressTask";

/**
 * A payload that can be used to gauge the progress of the parsing process.
 */
export type ProgressPayload = {
  /**
   * The details of the current progress.
   */
  details: ProgressDetails;
  /**
   * The current task.
   */
  currentTask: ProgressTask;
  /**
   * The estimated percentage of completion.
   */
  percentage: number;
  /**
   * The current total number of raws parsed.
   */
  runningTotal: number;
};
