// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tasks that describe what the parser is currently doing.
 */
export type ProgressTask =
  | "parseRaws"
  | "parseLegends"
  | "parseModuleInfoFiles"
  | "resolveRaws"
  | "idle";
