// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RawModuleLocation } from "./RawModuleLocation";

export interface ProgressDetails {
  location: RawModuleLocation;
  module: string | null;
  rawFile: string | null;
  fileLocation: string | null;
}
