// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::parser::RawModuleLocation

/**
 * Raws are part of modules since 50.xx. Raw modules are loaded from 3 common locations:
 * `{df_directory}/data/vanilla`, `{df_directory}/mods`, and `{df_directory/data/installed_mods}`
 */
export type RawModuleLocation =
  | "InstalledMods"
  | "Mods"
  | "Vanilla"
  | "Unknown"
  | "LegendsExport";
