// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::creature_variation::Rule

export type CreatureVariationRule =
  | "Unknown"
  | { RemoveTag: { tag: string; value: string | null } }
  | { NewTag: { tag: string; value: string | null } }
  | { AddTag: { tag: string; value: string | null } }
  | {
      ConvertTag: {
        tag: string;
        target: string | null;
        replacement: string | null;
      };
    }
  | {
      ConditionalNewTag: {
        tag: string;
        value: string | null;
        argument_index: string;
        argument_requirement: string;
      };
    }
  | {
      ConditionalAddTag: {
        tag: string;
        value: string | null;
        argument_index: string;
        argument_requirement: string;
      };
    }
  | {
      ConditionalRemoveTag: {
        tag: string;
        value: string | null;
        argument_index: string;
        argument_requirement: string;
      };
    }
  | {
      ConditionalConvertTag: {
        tag: string;
        target: string | null;
        replacement: string | null;
        argument_index: string;
        argument_requirement: string;
      };
    };
