// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { SingPlurName } from "./SingPlurName";

export type SeedMaterial = {
  name: SingPlurName;
  color: Color;
  material: string;
};
