// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RawMetadata } from "./RawMetadata";

export type SelectCreature = {
  metadata: RawMetadata | null;
  identifier: string;
  objectId: string;
  tags: Array<string>;
};
