// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::select_creature::SelectRules

export type SelectRules =
  | { selectCaste: string }
  | { selectMaterial: string }
  | { selectTissue: string }
  | { selectAdditionalCaste: string };
