// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::select_creature::SelectCreature

export type SelectCreature = {
  metadata: Metadata | null;
  identifier: string;
  objectId: string;
  tags: string[];
};
