// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::shrub::Shrub

export type Shrub = {
  growingSeason: SeasonToken[] | null;
  growDuration: number | null;
  value: number | null;
  pickedTile: number | null;
  deadPickedTile: number | null;
  shrubTile: number | null;
  deadShrubTile: number | null;
  clusterSize: number | null;
  pickedColor: Color | null;
  deadPickedColor: Color | null;
  shrubColor: Color | null;
  deadShrubColor: Color | null;
  shrubDrownLevel: number | null;
  drink: string | null;
  mill: string | null;
  thread: string | null;
  seed: SeedMaterial | null;
  extractStillVial: string | null;
  extractVial: string | null;
  extractBarrel: string | null;
};
