// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::shrub::Token

export type ShrubToken =
  | "Spring"
  | "Summer"
  | "Autumn"
  | "Winter"
  | "GrowDuration"
  | "Value"
  | "PickedTile"
  | "DeadPickedTile"
  | "ShrubTile"
  | "DeadShrubTile"
  | "ClusterSize"
  | "PickedColor"
  | "DeadPickedColor"
  | "ShrubColor"
  | "DeadShrubColor"
  | "ShrubDrownLevel"
  | "Drink"
  | "Mill"
  | "Thread"
  | "Seed"
  | "ExtractStillVial"
  | "ExtractVial"
  | "ExtractBarrel"
  | "Unknown";
