// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::parser::SingPlurName

/**
 * The name of a raw object with only singular and plural forms
 */
export type SingPlurName = { singular: string; plural: string };
