// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The name of a raw object with only singular and plural forms
 */
export type SingPlurName = { singular: string; plural: string };
