// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::graphics::SpriteLayer

export type SpriteLayer = {
  layerName: string;
  tilePageId: string;
  offset: Dimensions;
  offset2: Dimensions | null;
  largeImage: boolean | null;
  conditions: [Condition, string][] | null;
};
