// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::graphics::SpriteGraphic

export type SpriteGraphic = {
  primaryCondition: Condition;
  tilePageId: string;
  offset: Dimensions;
  color: ColorModification | null;
  largeImage: boolean | null;
  offset2: Dimensions | null;
  secondaryCondition: Condition | null;
  colorPalletSwap: number | null;
  targetIdentifier: string | null;
  extraDescriptor: string | null;
};
