// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorModification } from "./ColorModification";
import type { Condition } from "./Condition";
import type { Dimensions } from "./Dimensions";

export type SpriteGraphic = {
  primaryCondition: Condition;
  tilePageId: string;
  offset: Dimensions;
  color: ColorModification | null;
  largeImage: boolean | null;
  offset2: Dimensions | null;
  secondaryCondition: Condition | null;
  colorPalletSwap: number | null;
  targetIdentifier: string | null;
  extraDescriptor: string | null;
};
