// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::parser::StateName

/**
 * Represents the name of a materials 3 states (solid, liquid, gas)
 */
export type StateName = { solid: string; liquid: string; gas: string };
