// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the name of a materials 3 states (solid, liquid, gas)
 */
export type StateName = { solid: string; liquid: string; gas: string };
