// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::material::StateToken

export type MaterialState =
  | "Solid"
  | "Liquid"
  | "Gas"
  | "Powder"
  | "Paste"
  | "Pressed"
  | "Unknown"
  | "All"
  | "AllSolid";
