// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::parser::SteamData

/**
 * The additional data specific to the steam workshop
 */
export type SteamData = {
  title: string | null;
  description: string | null;
  tags: string[] | null;
  keyValueTags: string[] | null;
  metadata: string[] | null;
  changelog: string | null;
  fileId: string;
};
