// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The additional data specific to the steam workshop
 */
export type SteamData = {
  title: string | null;
  description: string | null;
  tags: Array<string> | null;
  keyValueTags: Array<string> | null;
  metadata: Array<string> | null;
  changelog: string | null;
  fileId: bigint;
};
