// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyndromeToken } from "./SyndromeToken";

export type Syndrome = {
  /**
   * Seen the \[SYN_IDENTIFIER:INEBRIATION\] tag in material_templates.txt
   */
  identifier: string | null;
  name: string | null;
  affectedClasses: Array<string> | null;
  immuneClasses: Array<string> | null;
  affectedCreatures: Array<[string, string]> | null;
  immuneCreatures: Array<[string, string]> | null;
  classes: Array<string> | null;
  /**
   * Seen the \[SYN_CONCENTRATION_ADDED:100:1000\] tag in material_templates.txt
   * default is 0:0
   */
  concentrationAdded: [number, number] | null;
  tags: Array<SyndromeToken> | null;
  conditions: Array<string> | null;
};
