// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::syndrome::Token

export type SyndromeToken =
  | "Name"
  | "Class"
  | "Injected"
  | "Contact"
  | "Inhaled"
  | "Ingested"
  | "AffectedClass"
  | "ImmuneClass"
  | "AffectedCreature"
  | "ImmuneCreature"
  | "ConcentrationAdded"
  | "NoHospital"
  | "Identifier"
  | "Unknown";
