// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::syndrome::Syndrome

export type Syndrome = {
  identifier: string | null;
  name: string | null;
  affectedClasses: string[] | null;
  immuneClasses: string[] | null;
  affectedCreatures: [string, string][] | null;
  immuneCreatures: [string, string][] | null;
  classes: string[] | null;
  concentrationAdded: number[] | null;
  tags: SyndromeToken[] | null;
  conditions: string[] | null;
};
