// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::parser::Temperatures

/**
 * The temperature properties of a material
 */
export type Temperatures = {
  specificHeat: number | null;
  ignitionPoint: number | null;
  meltingPoint: number | null;
  boilingPoint: number | null;
  heatDamagePoint: number | null;
  coldDamagePoint: number | null;
  materialFixedTemperature: number | null;
};
