// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The temperature properties of a material
 */
export type Temperatures = {
  /**
   * This determines how long it takes the material to heat up or cool down.
   * A material with a high specific heat capacity will hold more heat and affect its surroundings more
   * before cooling down or heating up to equilibrium. The input for this token is not temperature,
   * but rather the specific heat capacity of the material.
   */
  specificHeat: number | null;
  /**
   * This is the temperature at which the material will catch fire.
   */
  ignitionPoint: number | null;
  /**
   * This is the temperature at which a liquid material will freeze, or a solid material will melt.
   * In Dwarf Fortress the melting point and freezing point coincide exactly; this is contrary to many
   * real-life materials, which can be supercooled.
   */
  meltingPoint: number | null;
  /**
   * This is the temperature at which the material will boil or condense. Water boils at 10180 °U
   */
  boilingPoint: number | null;
  /**
   * This is the temperature above which the material will begin to take heat damage.
   * Burning items without a heat damage point (or with an exceptionally high one) will take damage very slowly,
   * causing them to burn for a very long time (9 months and 16.8 days) before disappearing.
   */
  heatDamagePoint: number | null;
  /**
   * This is the temperature below which the material will begin to take frost damage.
   */
  coldDamagePoint: number | null;
  /**
   * A material's temperature can be forced to always be a certain value via the `MAT_FIXED_TEMP`
   * material definition token. The only standard material which uses this is nether-cap wood,
   * whose temperature is always at the melting point of water. If a material's temperature is fixed
   * to between its cold damage point and its heat damage point, then items made from that material
   * will never suffer cold/heat damage. This makes nether-caps fire-safe and magma-safe despite being a type of wood.
   */
  materialFixedTemperature: number | null;
};
