// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::graphics::TilePage

export type TilePage = {
  metadata: Metadata | null;
  identifier: string;
  objectId: string;
  file: string;
  tileDim: Dimensions;
  pageDim: Dimensions;
};
