// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::parser::Tile

/**
 * Representation of a character tile (literally a single character) that is used in DF Classic
 */
export type Tile = {
  character: string;
  altCharacter: string | null;
  color: Color | null;
  glowCharacter: string | null;
  glowColor: Color | null;
};
