// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::tree::Tree

export type Tree = {
  material: string;
  trunkName: Name | null;
  maxTrunkHeight: number | null;
  maxTrunkDiameter: number | null;
  trunkPeriod: number | null;
  trunkWidthPeriod: number | null;
  branchName: Name | null;
  branchDensity: number | null;
  branchRadius: number | null;
  heavyBranchesName: Name | null;
  heavyBranchDensity: number | null;
  heavyBranchRadius: number | null;
  trunkBranching: number | null;
  rootName: Name | null;
  rootDensity: number | null;
  rootRadius: number | null;
  twigsName: Name | null;
  twigsPlacement: TwigPlacement[] | null;
  capName: Name | null;
  capPeriod: number | null;
  capRadius: number | null;
  treeTile: string | null;
  deadTreeTile: string | null;
  saplingTile: string | null;
  deadSaplingTile: string | null;
  treeColor: Color | null;
  deadTreeColor: Color | null;
  saplingColor: Color | null;
  deadSaplingColor: Color | null;
  saplingDrownLevel: number | null;
  treeDrownLevel: number | null;
  tags: TreeToken[] | null;
};
