// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { Name } from "./Name";
import type { TreeToken } from "./TreeToken";
import type { TwigPlacement } from "./TwigPlacement";

export type Tree = {
  /**
   * Tree will yield logs made of that material. Instead, if it's `[TREE:NONE]`, no logs will result.
   * Materials are typically found in other raws..
   */
  material: string;
  /**
   * What the trunk of the tree is named
   */
  trunkName: Name | null;
  /**
   * The maximum z-level height of the trunk, starting from +2 z-levels above the ground.
   * Valid values: 1-8
   * Default: 1
   */
  maxTrunkHeight: number | null;
  /**
   * Upper limit of trunk thickness, in tiles. Has a geometric effect on log yield.
   * Valid values: 1-3
   * Default: 1
   */
  maxTrunkDiameter: number | null;
  /**
   * The number of years the trunk takes to grow one z-level upward. Default: 1
   */
  trunkPeriod: number | null;
  /**
   * The number of years the trunk takes to grow one tile wider. Default: 1
   */
  trunkWidthPeriod: number | null;
  /**
   * What thin branches of the tree are named.
   */
  branchName: Name | null;
  /**
   * How dense the branches grow on this tree.
   */
  branchDensity: number | null;
  /**
   * The radius to which branches can reach. Appears to never reach further than seven tiles from the centre.
   * Does not depend on the trunk branching amount or where trunks are.
   * The values used in the game go from 0-3. Higher values than that can cause crashes.
   */
  branchRadius: number | null;
  /**
   * What thick branches of the tree are named.
   */
  heavyBranchesName: Name | null;
  /**
   * Similar to BRANCH_DENSITY for thick branches. Default: 0
   */
  heavyBranchDensity: number | null;
  /**
   * Similar as BRANCH_DENSITY for thick branches. Values outside 0-3 can cause crashes. Default: 0
   */
  heavyBranchRadius: number | null;
  /**
   * How much the trunk branches out. 0 makes the trunk straight (default)
   */
  trunkBranching: number | null;
  /**
   * What the roots of the tree are named.
   */
  rootName: Name | null;
  /**
   * Density of the root growth. Defaults to 0.
   */
  rootDensity: number | null;
  /**
   * How wide the roots reach out. Defaults to 0.
   */
  rootRadius: number | null;
  /**
   * What the twigs of the tree are named.
   */
  twigsName: Name | null;
  /**
   * Where twigs appear, defaults to [SideBranches, AboveBranches]
   */
  twigsPlacement: Array<TwigPlacement> | null;
  /**
   * What this mushroom-cap is called. Only makes sense with TREE_HAS_MUSHROOM_CAP.
   */
  capName: Name | null;
  /**
   * Similar to the other PERIOD tags, influences the rate of the mushroom cap growth. Only makes sense with TREE_HAS_MUSHROOM_CAP. Default: 1
   */
  capPeriod: number | null;
  /**
   * The radius of a mushroom cap. Only makes sense with TREE_HAS_MUSHROOM_CAP. Default: 0
   */
  capRadius: number | null;
  /**
   * The tile used for trees of this type on the world map. Defaults to 24 (↑).
   */
  treeTile: string | null;
  /**
   * The tile used for (un)dead trees and deciduous trees (generally in winter) of this type. Defaults to 198 (╞).
   */
  deadTreeTile: string | null;
  /**
   * The tile used for saplings of this tree. Defaults to 231 (τ).
   */
  saplingTile: string | null;
  /**
   * The tile used for dead saplings of this tree. Defaults to 231 (τ).
   */
  deadSaplingTile: string | null;
  /**
   * The color of the tree on the map. Defaults to 2:0:0 (dark green).
   */
  treeColor: Color | null;
  /**
   * The color of the tree on the map when (un)dead. Defaults to 0:0:1 (dark gray).
   */
  deadTreeColor: Color | null;
  /**
   * The color of saplings of this tree. Defaults to 2:0:0 (dark green).
   */
  saplingColor: Color | null;
  /**
   * The color of dead saplings of this tree. Defaults to 0:0:1 (dark gray).
   */
  deadSaplingColor: Color | null;
  /**
   * The sapling of this tree will drown once the water on its tile reaches this level. Defaults to 4.
   */
  saplingDrownLevel: number | null;
  /**
   * The water depth at which this tree will drown. Exact behavior is unknown. Defaults to 7.
   */
  treeDrownLevel: number | null;
  /**
   * Token tags for the tree.
   */
  tags: Array<TreeToken> | null;
};
