// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::tree::TwigPlacementToken

export type TwigPlacement =
  | "SideBranches"
  | "AboveBranches"
  | "BelowBranches"
  | "SideHeavyBranches"
  | "AboveHeavyBranches"
  | "BelowHeavyBranches"
  | "SideTrunk"
  | "AboveTrunk"
  | "BelowTrunk"
  | "Unknown";
