// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::material::TypeToken

export type MaterialType =
  | "Inorganic"
  | "Stone"
  | "Metal"
  | "Coal"
  | "CreatureMaterial"
  | "LocalCreatureMaterial"
  | "PlantMaterial"
  | "LocalPlantMaterial"
  | "GetMaterialFromReagent"
  | "Amber"
  | "Coral"
  | "GlassGreen"
  | "GlassClear"
  | "GlassCrystal"
  | "Water"
  | "Potash"
  | "Ash"
  | "PearlAsh"
  | "Lye"
  | "Mud"
  | "Vomit"
  | "Salt"
  | "FilthB"
  | "FilthY"
  | "UnknownSubstance"
  | "Grime"
  | "Unknown";
