// File generated by specta. Do not edit!
//
/// lib/dfraw_json_parser::unprocessed_raw::UnprocessedRaw

export type UnprocessedRaw = {
  rawType: ObjectType;
  modifications: Modification[];
  metadata: Metadata;
  identifier: string;
};
