[package]
name = "dfraw_json_parser"
version = "0.12.0"
edition = "2021"
authors = ["Nicholas Westerhausen <nick@westmail.cc>"]
description = "Library which parses Dwarf Fortress raw files into JSON"
repository = "https://github.com/nwesterhausen/dfraw_json_parser.git"
license = "MIT"
homepage = "https://github.com/nwesterhausen/dfraw_json_parser"
keywords = ["dwarf_fortress", "JSON", "parsing"]
categories = ["parsing"]

[lib]
name = "dfraw_json_parser"
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
tauri = ["dep:tauri"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8"
encoding_rs_io = "0.1"
lazy_static = "1.4.0"
log = "0.4.17"
regex = "1.7"
serde_json = "1.0"
slug = "0.1"
titlecase = "2.2.1"
walkdir = "2"
# Tauri feature dependency needs tauri lib
tauri = { version = "1.2", optional = true }

[dependencies.phf]
version = "0.11.1"
default-features = true
features = ["macros"]

[dependencies.serde]
version = "1"
default-features = true
features = ["derive"]

[dev-dependencies]
chrono = "0.4"

[dev-dependencies.fern]
version = "0.6.1"
features = ["colored"]

[dev-dependencies.clap]
version = "4.1"
default-features = true
features = ["derive"]
