use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, PartialEq, Eq)]
pub enum DFTag {
    // Creature Tags
    ArtificialHiveable,
    DoesNotExist,
    Evil,
    Fanciful,
    Good,
    Savage,
    Generated,
    Ubiquitous,
    VerminSoil,
    VerminSoilColony,
    VerminRotter,
    VerminGrounder,
    VerminFish,
    VerminEater,
    LargeRoaming,
    LocalPopsControllable,
    LocalPopsProduceHeroes,
    LooseClusters,
    Mundane,
    // Inorganic Tags
    Sedimentary,
    Aquifer,
    SedimentaryOceanShallow,
    SedimentaryOceanDeep,
    IgneousIntrusive,
    IgneousExtrusive,
    Metamorphic,
    Soil,
    SoilOcean,
    Wafers,
    DeepSpecial,
    DeepSurface,
    Lava,
    Special,
    //Generated,
    Divine,
    SoilSand,
    // Plant Tags
    Dry,
    //Evil,
    //Good,
    //Savage,
    Wet,
    Spring,
    Summer,
    Autumn,
    Winter,
    Brewable,
    // Contaminate Tags
    Blood,
    Slime,
    Vomit,
    Ichor,
    Pus,
    Goo,
    Grime,
    Filth,
    // Material State Tags
    Solid,
    Liquid,
    Gas,
    Powder,
    Paste,
    Pressed,
    All,
    AllSolid,
    // Material Tags
    Alcohol,
    AlcoholCreature,
    AlcoholPlant,
    Bone,
    Cheese,
    CheeseCreature,
    CheesePlant,
    CrystalGlassable,
    DisplayUnglazed,
    DoNotCleanGlob,
    EdibleCooked,
    EdibleRaw,
    EdibleVermin,
    EntersBlood,
    Evaporates,
    Feather,
    GeneratesMiasma,
    Horn,
    Hoof,
    ImpliesAnimalKill,
    IsCeramic,
    IsGlass,
    IsMetal,
    IsStone,
    ItemsAmmo,
    ItemsAnvil,
    ItemsArmor,
    ItemsBarred,
    ItemsDelicate,
    ItemsDigger,
    ItemsHard,
    ItemsLeather,
    ItemsMetal,
    ItemsQuern,
    ItemsScaled,
    ItemsSiegeEngine,
    ItemsSoft,
    ItemsWeapon,
    ItemsWeaponRanged,
    Leather,
    LiquidMisc,
    LiquidMiscCreature,
    LiquidMiscOther,
    LiquidMiscPlant,
    MapDescriptorBlood,
    MapDescriptorGoo,
    MapDescriptorIchor,
    MapDescriptorPus,
    MapDescriptorSlime,
    MapDescriptorSpit,
    MapDescriptorSweat,
    MapDescriptorTears,
    Meat,
    NoStoneStockpile,
    Pearl,
    PowderMisc,
    PowderMiscCreature,
    PowderMiscPlant,
    Rots,
    SeedMaterial,
    Shell,
    Silk,
    Soap,
    StockpileGlob,
    StockpileGlobPaste,
    StockpileGlobPressed,
    StockpileGlobSolid,
    StockpilePlantGrowth,
    StockpileThreadMaterial,
    StructuralPlantMaterial,
    ThreadPlant,
    Tooth,
    Undiggable,
    //Wafers,
    Wood,
    Yarn,
    // Syndrome Tags
    Contact,
    Ingested,
    Inhaled,
    Injected,
    NoHospital,
    // Effect Tags
    Localized,
    OnlyVascular,
    OnlyMuscular,
    SizeDilutes,
    SizeDelays,
    CanBeHidden,
    Resistible, // Resist​able in raws
    Abrupt,
    // Effect Condition Tags
    Bruising,
    Blisters,
    Oozing,
    Bleeding,
    Swelling,
    Necrosis,
    Numbness,
    Pain,
    Paralysis,
    ImpairFunction,
    Dizziness,
    Drowsiness,
    Unconsciousness,
    Fever,
    Nausea,
    CoughBlood,
    VomitBlood,

    ReducePain,
    ReduceSwelling,
    ReduceParalysis,
    ReduceDizziness,
    ReduceNausea,
    ReduceFever,
    StopBleeding,
    CloseOpenWounds,
    CureInfection,
    HealTissues,
    HealNerves,
    RegrowParts,
    // Caste Tags
    LaysEggs,
    AmbushPredator,
    Amphibious,
    AdoptsOwner,
    Benign,
    Aquatic,
    ArenaRestricted,
    AtPeaceWithWildlife,
    BoneCarn,
    CanLearn,
    CanSpeak,
    Carnivore,
    CommonDomestic,
    CookableLive,
    Demon,
    DieWhenVerminBite,
    Equips,
    Extravision,
    FeatureBeast,
    Female,
    FireImmune,
    FireimmuneSuper,
    FishItem,
    Flier,
    Gnawer,
    HasNerves,
    HuntsVermin,
    Immobile,
    ImmobileLand,
    Immolate,
    Intelligent,
    LightGen,
    LockPicker,
    MagmaVision,
    Male,
    Meanderer,
    Megabeast,
    Mischievous,
    Mount,
    MountExotic,
    MultipartFullVision,
    MultipleLitterRare,
    Natural,
    NoConnectionsForMovement,
    NoDizziness,
    NoDrink,
    NoEat,
    NoFevers,
    NoGender,
    NoSleep,
    NoBones,
    NoBreathe,
    NoEmotion,
    NoExert,
    NoFear,
    NoMeat,
    NoNausea,
    NoPain,
    NoSkin,
    NoSkull,
    NoSmellyRot,
    NoStuckIns,
    NoStun,
    NotButcherable,
    NotLiving,
    NoThought,
    OpposedToLife,
    OutsiderControllable,
    PackAnimal,
    ParalyzeImmune,
    Pet,
    PetExotic,
    Power,
    SemiMegabeast,
    SlowLearner,
    SmallRemains,
    StandardGrazer, //Acts as [GRAZER] but set to 20000*G*(max size)^(-3/4)
    Supernatural,
    SwimsInnate,
    SwimsLearned,
    ThickWeb,
    Titan,
    Trances,
    TrapAvoid,
    UniqueDemon,
    Vegetation,
    VerminHateable,
    VerminMicro,
    VerminNofish,
    VerminNoroam,
    VerminNotrap,
    WagonPuller,
    WebImmune,
    // Material Tags
    Hard,
    Metal,
    MetalWeapon,
    // Catchall
    Unknown,
}

impl DFTag {
    // match the provided string and return the enum variant
    #[allow(clippy::too_many_lines)]
    pub fn from_string(tag_key: &str) -> Self {
        match tag_key {
            // Creature Tags
            "ARTIFICIAL_HIVEABLE" => DFTag::ArtificialHiveable,
            "DOES_NOT_EXIST" => DFTag::DoesNotExist,
            "EVIL" => DFTag::Evil,
            "FANCIFUL" => DFTag::Fanciful,
            "GOOD" => DFTag::Good,
            "SAVAGE" => DFTag::Savage,
            "GENERATED" => DFTag::Generated,
            "UBIQUITOUS" => DFTag::Ubiquitous,
            "VERMIN_SOIL" => DFTag::VerminSoil,
            "VERMIN_SOIL_COLONY" => DFTag::VerminSoilColony,
            "VERMIN_ROTTER" => DFTag::VerminRotter,
            "VERMIN_GROUNDER" => DFTag::VerminGrounder,
            "VERMIN_FISH" => DFTag::VerminFish,
            "VERMIN_EATER" => DFTag::VerminEater,
            "LARGE_ROAMING" => DFTag::LargeRoaming,
            "LOCAL_POPS_CONTROLLABLE" => DFTag::LocalPopsControllable,
            "LOCAL_POPS_PRODUCE_HEROES" => DFTag::LocalPopsProduceHeroes,
            "LOOSE_CLUSTERS" => DFTag::LooseClusters,
            "MUNDANE" => DFTag::Mundane,
            // Inorganic Tags
            "SEDIMENTARY" => DFTag::Sedimentary,
            "AQUIFER" => DFTag::Aquifer,
            "SEDIMENTARY_OCEAN_SHALLOW" => DFTag::SedimentaryOceanShallow,
            "SEDIMENTARY_OCEAN_DEEP" => DFTag::SedimentaryOceanDeep,
            "IGNEOUS_INTRUSIVE" => DFTag::IgneousIntrusive,
            "IGNEOUS_EXTRUSIVE" => DFTag::IgneousExtrusive,
            "METAMORPHIC" => DFTag::Metamorphic,
            "SOIL" => DFTag::Soil,
            "SOIL_OCEAN" => DFTag::SoilOcean,
            "WAFERS" => DFTag::Wafers,
            "DEEP_SPECIAL" => DFTag::DeepSpecial,
            "DEEP_SURFACE" => DFTag::DeepSurface,
            "LAVA" => DFTag::Lava,
            "SPECIAL" => DFTag::Special,
            //"GENERATED" => DFTag::Generated,
            "DIVINE" => DFTag::Divine,
            "SOIL_SAND" => DFTag::SoilSand,
            // Plant Tags
            "DRY" => DFTag::Dry,
            //"EVIL" => DFTag::Evil,
            //"GOOD" => DFTag::Good,
            //"SAVAGE" => DFTag::Savage,
            "WET" => DFTag::Wet,
            "SPRING" => DFTag::Spring,
            "SUMMER" => DFTag::Summer,
            "AUTUMN" => DFTag::Autumn,
            "WINTER" => DFTag::Winter,
            "BREWABLE" => DFTag::Brewable,
            // Contaminate Tags
            "BLOOD" => DFTag::Blood,
            "SLIME" => DFTag::Slime,
            "VOMIT" => DFTag::Vomit,
            "ICHOR" => DFTag::Ichor,
            "PUS" => DFTag::Pus,
            "GOO" => DFTag::Goo,
            "GRIME" => DFTag::Grime,
            "FILTH" => DFTag::Filth,
            // Material State Tags
            "SOLID" => DFTag::Solid,
            "LIQUID" => DFTag::Liquid,
            "GAS" => DFTag::Gas,
            "POWDER" => DFTag::Powder,
            "PASTE" => DFTag::Paste,
            "PRESSED" => DFTag::Pressed,
            "ALL" => DFTag::All,
            "ALL_SOLID" => DFTag::AllSolid,
            // Material Tags
            "ALCOHOL" => DFTag::Alcohol,
            "ALCOHOL_CREATURE" => DFTag::AlcoholCreature,
            "ALCOHOL_PLANT" => DFTag::AlcoholPlant,
            "BONE" => DFTag::Bone,
            "CHEESE" => DFTag::Cheese,
            "CHEESE_CREATURE" => DFTag::CheeseCreature,
            "CHEESE_PLANT" => DFTag::CheesePlant,
            "CRYSTAL_GLASSABLE" => DFTag::CrystalGlassable,
            "DISPLAY_UNGLAZED" => DFTag::DisplayUnglazed,
            "DO_NOT_CLEAN_GLOB" => DFTag::DoNotCleanGlob,
            "EDIBLE_COOKED" => DFTag::EdibleCooked,
            "EDIBLE_RAW" => DFTag::EdibleRaw,
            "EDIBLE_VERMIN" => DFTag::EdibleVermin,
            "ENTERS_BLOOD" => DFTag::EntersBlood,
            "EVAPORATES" => DFTag::Evaporates,
            "FEATHER" => DFTag::Feather,
            "GENERATES_MIASMA" => DFTag::GeneratesMiasma,
            "HORN" => DFTag::Horn,
            "HOOVES" => DFTag::Hoof,
            "IMPLIES_ANIMAL_KILL" => DFTag::ImpliesAnimalKill,
            "IS_CERAMIC" => DFTag::IsCeramic,
            "IS_GLASS" => DFTag::IsGlass,
            "IS_METAL" => DFTag::IsMetal,
            "IS_STONE" => DFTag::IsStone,
            "ITEMS_AMMO" => DFTag::ItemsAmmo,
            "ITEMS_ARMOR" => DFTag::ItemsArmor,
            "ITEMS_BARRED" => DFTag::ItemsBarred,
            "ITEMS_DELICATE" => DFTag::ItemsDelicate,
            "ITEMS_DIGGER" => DFTag::ItemsDigger,
            "ITEMS_HARD" => DFTag::ItemsHard,
            "ITEMS_LEATHER" => DFTag::ItemsLeather,
            "ITEMS_METAL" => DFTag::ItemsMetal,
            "ITEMS_QUERN" => DFTag::ItemsQuern,
            "ITEMS_SCALED" => DFTag::ItemsScaled,
            "ITEMS_SIEGE_ENGINE" => DFTag::ItemsSiegeEngine,
            "ITEMS_SOFT" => DFTag::ItemsSoft,
            "ITEMS_WEAPON" => DFTag::ItemsWeapon,
            "ITEMS_WEAPON_RANGED" => DFTag::ItemsWeaponRanged,
            "LEATHER" => DFTag::Leather,
            "LIQUID_MISC" => DFTag::LiquidMisc,
            "LIQUID_MISC_CREATURE" => DFTag::LiquidMiscCreature,
            "LIQUID_MISC_OTHER" => DFTag::LiquidMiscOther,
            "LIQUID_MISC_PLANT" => DFTag::LiquidMiscPlant,
            "MAP_DESCRIPTOR_BLOOD" => DFTag::MapDescriptorBlood,
            "MAP_DESCRIPTOR_GOO" => DFTag::MapDescriptorGoo,
            "MAP_DESCRIPTOR_ICHOR" => DFTag::MapDescriptorIchor,
            "MAP_DESCRIPTOR_PUS" => DFTag::MapDescriptorPus,
            "MAP_DESCRIPTOR_SLIME" => DFTag::MapDescriptorSlime,
            "MAP_DESCRIPTOR_SPIT" => DFTag::MapDescriptorSpit,
            "MAP_DESCRIPTOR_SWEAT" => DFTag::MapDescriptorSweat,
            "MAP_DESCRIPTOR_TEARS" => DFTag::MapDescriptorTears,
            "MEAT" => DFTag::Meat,
            "NO_STONE_STOCKPILE" => DFTag::NoStoneStockpile,
            "PEARL" => DFTag::Pearl,
            "POWDER_MISC" => DFTag::PowderMisc,
            "POWDER_MISC_CREATURE" => DFTag::PowderMiscCreature,
            "POWDER_MISC_PLANT" => DFTag::PowderMiscPlant,
            "ROTS" => DFTag::Rots,
            "SEED_MATERIAL" => DFTag::SeedMaterial,
            "SHELL" => DFTag::Shell,
            "SILK" => DFTag::Silk,
            "SOAP" => DFTag::Soap,
            "STOCKPILE_GLOB" => DFTag::StockpileGlob,
            "STOCKPILE_GLOB_PASTE" => DFTag::StockpileGlobPaste,
            "STOCKPILE_GLOB_PRESSED" => DFTag::StockpileGlobPressed,
            "STOCKPILE_GLOB_SOLID" => DFTag::StockpileGlobSolid,
            "STOCKPILE_PLANT_GROWTH" => DFTag::StockpilePlantGrowth,
            "STOCKPILE_THREAD_MATERIAL" => DFTag::StockpileThreadMaterial,
            "STRUCTURAL_PLANT_MAT" => DFTag::StructuralPlantMaterial,
            "THREAD_PLANT" => DFTag::ThreadPlant,
            "TOOTH" => DFTag::Tooth,
            "UNDIGGABLE" => DFTag::Undiggable,
            //"WAFERS" => DFTag::Wafers,
            "WOOD" => DFTag::Wood,
            "YARN" => DFTag::Yarn,
            // Syndrome Tags
            "CONTACT" => DFTag::Contact,
            "INGESTED" => DFTag::Ingested,
            "INHALED" => DFTag::Inhaled,
            "INJECTED" => DFTag::Injected,
            "NO_HOSPITAL" => DFTag::NoHospital,
            // Effect Tags
            "LOCALIZED" => DFTag::Localized,
            "ONLY_VASCULAR" => DFTag::OnlyVascular,
            "ONLY_MUSCULAR" => DFTag::OnlyMuscular,
            "SIZE_DILUTES" => DFTag::SizeDilutes,
            "SIZE_DELAYS" => DFTag::SizeDelays,
            "CAN_BE_HIDDEN" => DFTag::CanBeHidden,
            "RESISTIBLE" => DFTag::Resistible,
            "ABRUPT" => DFTag::Abrupt,
            // Effect Condition Tags
            "BRUISING" => DFTag::Bruising,
            "BLISTERS" => DFTag::Blisters,
            "OOZING" => DFTag::Oozing,
            "BLEEDING" => DFTag::Bleeding,
            "SWELLING" => DFTag::Swelling,
            "NECROSIS" => DFTag::Necrosis,
            "NUMBNESS" => DFTag::Numbness,
            "PAIN" => DFTag::Pain,
            "PARALYSIS" => DFTag::Paralysis,
            "IMPAIR_FUNCTION" => DFTag::ImpairFunction,
            "DIZZINESS" => DFTag::Dizziness,
            "DROWSINESS" => DFTag::Drowsiness,
            "UNCONSCIOUSNESS" => DFTag::Unconsciousness,
            "FEVER" => DFTag::Fever,
            "NAUSEA" => DFTag::Nausea,
            "COUGH_BLOOD" => DFTag::CoughBlood,
            "VOMIT_BLOOD" => DFTag::VomitBlood,

            "REDUCE_PAIN" => DFTag::ReducePain,
            "REDUCE_SWELLING" => DFTag::ReduceSwelling,
            "REDUCE_PARALYSIS" => DFTag::ReduceParalysis,
            "REDUCE_DIZZINESS" => DFTag::ReduceDizziness,
            "REDUCE_NAUSEA" => DFTag::ReduceNausea,
            "REDUCE_FEVER" => DFTag::ReduceFever,
            "STOP_BLEEDING" => DFTag::StopBleeding,
            "CLOSE_OPEN_WOUNDS" => DFTag::CloseOpenWounds,
            "CURE_INFECTION" => DFTag::CureInfection,
            "HEAL_TISSUES" => DFTag::HealTissues,
            "HEAL_NERVES" => DFTag::HealNerves,
            "REGROW_PARTS" => DFTag::RegrowParts,
            // Caste Tags
            "LAYS_EGGS" => DFTag::LaysEggs,
            "AMBUSH_PREDATOR" => DFTag::AmbushPredator,
            "AMPHIBIOUS" => DFTag::Amphibious,
            "ADOPTS_OWNER" => DFTag::AdoptsOwner,
            "BENIGN" => DFTag::Benign,
            "AQUATIC" => DFTag::Aquatic,
            "ARENA_RESTRICTED" => DFTag::ArenaRestricted,
            "AT_PEACE_WITH_WILDLIFE" => DFTag::AtPeaceWithWildlife,
            "BONECARN" => DFTag::BoneCarn,
            "CAN_LEARN" => DFTag::CanLearn,
            "CAN_SPEAK" => DFTag::CanSpeak,
            "CARNIVORE" => DFTag::Carnivore,
            "COMMON_DOMESTIC" => DFTag::CommonDomestic,
            "COOKABLE_LIVE" => DFTag::CookableLive,
            "DEMON" => DFTag::Demon,
            "DIE_WHEN_VERMIN_BITE" => DFTag::DieWhenVerminBite,
            "EQUIPS" => DFTag::Equips,
            "EXTRAVISION" => DFTag::Extravision,
            "FEATURE_BEAST" => DFTag::FeatureBeast,
            "FEMALE" => DFTag::Female,
            "FIREIMMUNE" => DFTag::FireImmune,
            "FIREIMMUNE_SUPER" => DFTag::FireimmuneSuper,
            "FISHITEM" => DFTag::FishItem,
            "FLIER" => DFTag::Flier,
            "GNAWER" => DFTag::Gnawer,
            "HAS_NERVES" => DFTag::HasNerves,
            "HUNTS_VERMIN" => DFTag::HuntsVermin,
            "IMMOBILE" => DFTag::Immobile,
            "IMMOBILE_LAND" => DFTag::ImmobileLand,
            "IMMOLATE" => DFTag::Immolate,
            "INTELLIGENT" => DFTag::Intelligent,
            "LIGHT_GEN" => DFTag::LightGen,
            "LOCKPICKER" => DFTag::LockPicker,
            "MAGMA_VISION" => DFTag::MagmaVision,
            "MALE" => DFTag::Male,
            "MEANDERER" => DFTag::Meanderer,
            "MEGABEAST" => DFTag::Megabeast,
            "MISCHIEVOUS" | "MISCHIEVIOUS" => DFTag::Mischievous,
            "MOUNT" => DFTag::Mount,
            "MOUNT_EXOTIC" => DFTag::MountExotic,
            "MULTIPART_FULLVISION" => DFTag::MultipartFullVision,
            "MULTIPLE_LITTER_RARE" => DFTag::MultipleLitterRare,
            "NATURAL" => DFTag::Natural,
            "NO_CONNECTIONS_FOR_MOVEMENT" => DFTag::NoConnectionsForMovement,
            "NO_DIZZINESS" => DFTag::NoDizziness,
            "NO_DRINK" => DFTag::NoDrink,
            "NO_EAT" => DFTag::NoEat,
            "NO_FEVERS" => DFTag::NoFevers,
            "NO_GENDER" => DFTag::NoGender,
            "NO_SLEEP" => DFTag::NoSleep,
            "NOBONES" => DFTag::NoBones,
            "NOBREATHE" => DFTag::NoBreathe,
            "NOEMOTION" => DFTag::NoEmotion,
            "NOEXERT" => DFTag::NoExert,
            "NOFEAR" => DFTag::NoFear,
            "NOMEAT" => DFTag::NoMeat,
            "NONAUSEA" => DFTag::NoNausea,
            "NOPAIN" => DFTag::NoPain,
            "NOSKIN" => DFTag::NoSkin,
            "NOSKULL" => DFTag::NoSkull,
            "NOSMELLYROT" => DFTag::NoSmellyRot,
            "NOSTUCKINS" => DFTag::NoStuckIns,
            "NOSTUN" => DFTag::NoStun,
            "NOT_BUTCHERABLE" => DFTag::NotButcherable,
            "NOT_LIVING" => DFTag::NotLiving,
            "NOTHOUGHT" => DFTag::NoThought,
            "OPPOSED_TO_LIFE" => DFTag::OpposedToLife,
            "OUTSIDER_CONTROLLABLE" => DFTag::OutsiderControllable,
            "PACK_ANIMAL" => DFTag::PackAnimal,
            "PARALYZEIMMUNE" => DFTag::ParalyzeImmune,
            "PET" => DFTag::Pet,
            "PET_EXOTIC" => DFTag::PetExotic,
            "POWER" => DFTag::Power,
            "SEMIMEGABEAST" => DFTag::SemiMegabeast,
            "SLOW_LEARNER" => DFTag::SlowLearner,
            "SMALL_REMAINS" => DFTag::SmallRemains,
            "STANDARD_GRAZER" => DFTag::StandardGrazer,
            "SUPERNATURAL" => DFTag::Supernatural,
            "SWIMS_INNATE" => DFTag::SwimsInnate,
            "SWIMS_LEARNED" => DFTag::SwimsLearned,
            "THICKWEB" => DFTag::ThickWeb,
            "TITAN" => DFTag::Titan,
            "TRANCES" => DFTag::Trances,
            "TRAPAVOID" => DFTag::TrapAvoid,
            "UNIQUE_DEMON" => DFTag::UniqueDemon,
            "VEGETATION" => DFTag::Vegetation,
            "VERMIN_HATEABLE" => DFTag::VerminHateable,
            "VERMIN_MICRO" => DFTag::VerminMicro,
            "VERMIN_NOFISH" => DFTag::VerminNofish,
            "VERMIN_NOROAM" => DFTag::VerminNoroam,
            "VERMIN_NOTRAP" => DFTag::VerminNotrap,
            "WAGON_PULLER" => DFTag::WagonPuller,
            "WEBIMMUNE" => DFTag::WebImmune,
            // Material Tags
            "HARD" => DFTag::Hard,
            "METAL" => DFTag::Metal,
            "METAL_WEAPON" => DFTag::MetalWeapon,
            // Catchall
            _ => {
                log::warn!("Unknown tag: {}", tag_key);
                DFTag::Unknown
            }
        }
    }
}
