use serde::{Deserialize, Serialize};

#[derive(ts_rs::TS)]
#[ts(export)]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Default)]
pub enum CreatureTag {
    ArtificialHiveable,
    DoesNotExist,
    Evil,
    Fanciful,
    Good,
    Savage,
    Generated,
    Ubiquitous,
    VerminSoil,
    VerminSoilColony,
    VerminRotter,
    VerminGrounder,
    VerminFish,
    VerminEater,
    LargeRoaming,
    LocalPopsControllable,
    LocalPopsProduceHeroes,
    LooseClusters,
    Mundane,
    Biome,
    PrefString,
    Name,
    GeneralBabyName,
    GeneralChildName,
    Frequency,
    UndergroundDepth,
    PopulationNumber,
    CopyTagsFrom,
    ApplyCreatureVariation,
    CreatureTile,
    AltTile,
    Color,
    GlowColor,
    GlowTile,
    ChangeFrequencyPercent,
    ClusterNumber,
    #[default]
    Unknown,
}
