use super::tokens::CasteTag;

pub static CASTE_TOKENS: phf::Map<&'static str, CasteTag> = phf::phf_map! {
    "ADOPTS_OWNER" => CasteTag::AdoptsOwner,
    "ALCOHOL_DEPENDENT" => CasteTag::AlcoholDependent,
    "ALL_ACTIVE" => CasteTag::AllActive,
    "CASTE_ALTTILE" => CasteTag::AltTile {
        tile: String::new(),
    },
    "AMBUSHPREDATOR" => CasteTag::AmbushPredator,
    "AMPHIBIOUS" => CasteTag::Amphibious,
    "APPLY_CREATURE_VARIATION" => CasteTag::ApplyCreatureVariation {
        id: String::new(),
        args: Vec::new(),
    },
    "APPLY_CURRENT_CREATURE_VARIATION" => CasteTag::ApplyCurrentCreatureVariation,
    "AQUATIC" => CasteTag::Aquatic,
    "ARENA_RESTRICTED" => CasteTag::ArenaRestricted,
    "AT_PEACE_WITH_WILDLIFE" => CasteTag::AtPeaceWithWildlife,
    "ATTACK" => CasteTag::Attack { name: String::new(), body_part: String::new() },
    "ATTACK_TRIGGER" => CasteTag::AttackTrigger { population: 0, exported_wealth: 0, created_wealth: 0 },
    "BABY" => CasteTag::Baby { age: 0 },
    "BABYNAME" => CasteTag::BabyName { singular: String::new(), plural: String::new() },
    "BEACH_FREQUENCY" => CasteTag::BeachFrequency { frequency: 0 },
    "BENIGN" => CasteTag::Benign,
    "BLOOD" => CasteTag::Blood { material: String::new(), state: String::new() },
    "BLOODSUCKER" => CasteTag::BloodSucker,
    "BODY" => CasteTag::Body { body_parts: Vec::new() },
    "BODY_APPEARANCE_MODIFIER" => CasteTag::BodyAppearanceModifier { attribute: String::new(), values: [0,0,0,0,0,0,0] },
    "BODY_DETAIL_PLAN" => CasteTag::BodyDetailPlan { body_plan: String::new(), arguments: Vec::new() },
    "BODY_SIZE" => CasteTag::BodySize { year: 0, days: 0, size: 0 },
    "BODYGLOSS" => CasteTag::BodyGloss { gloss: String::new() },
    "BONECARN" => CasteTag::BoneCarn,
    "BP_ADD_TYPE" => CasteTag::BodyPartAddType { body_part_type: String::new() },
    "BP_APPEARANCE_MODIFIER" => CasteTag::BodyPartAppearanceModifier { quality: String::new(), spread: [0,0,0,0,0,0,0] },
    "BP_REMOVE_TYPE" => CasteTag::BodyPartRemoveType { body_part_type: String::new() },
    "BUILDINGDESTROYER" => CasteTag::BuildingDestroyer {door_and_furniture_focused: false},
};
