use crate::tags::CreatureEffectTag;

/// A map of creature effect tokens to their strings.
pub static CREATURE_EFFECT_TOKENS: phf::Map<&'static str, CreatureEffectTag> = phf::phf_map! {
    "CE_PAIN" => CreatureEffectTag::Pain,
    "CE_SWELLING" => CreatureEffectTag::Swelling,
    "CE_OOZING" => CreatureEffectTag::Oozing,
    "CE_BRUISING" => CreatureEffectTag::Bruising,
    "CE_BLISTERS" => CreatureEffectTag::Blisters,
    "CE_NUMBNESS" => CreatureEffectTag::Numbness,
    "CE_PARALYSIS" => CreatureEffectTag::Paralysis,
    "CE_FEVER" => CreatureEffectTag::Fever,
    "CE_BLEEDING" => CreatureEffectTag::Bleeding,
    "CE_COUGHING_BLOOD" => CreatureEffectTag::CoughingBlood,
    "CE_VOMITING_BLOOD" => CreatureEffectTag::VomitingBlood,
    "CE_VOMIT_BLOOD" => CreatureEffectTag::VomitingBlood,
    "CE_NAUSEA" => CreatureEffectTag::Nausea,
    "CE_UNCONSCIOUSNESS" => CreatureEffectTag::Unconsciousness,
    "CE_NECROSIS" => CreatureEffectTag::Necrosis,
    "CE_IMPAIR_FUNCTION" => CreatureEffectTag::ImpairFunction,
    "CE_DROWSINESS" => CreatureEffectTag::Drowsiness,
    "CE_DIZZINESS" => CreatureEffectTag::Dizziness,

    "CE_REDUCE_PAIN" => CreatureEffectTag::ReducePain,
    "CE_REDUCE_SWELLING" => CreatureEffectTag::ReduceSwelling,
    "CE_REDUCE_PARALYSIS" => CreatureEffectTag::ReduceParalysis,
    "CE_REDUCE_DIZZINESS" => CreatureEffectTag::ReduceDizziness,
    "CE_REDUCE_NAUSEA" => CreatureEffectTag::ReduceNausea,
    "CE_REDUCE_FEVER" => CreatureEffectTag::ReduceFever,
    "CE_STOP_BLEEDING" => CreatureEffectTag::StopBleeding,
    "CE_CLOSE_OPEN_WOUNDS" => CreatureEffectTag::CloseOpenWounds,
    "CE_CURE_INFECTION" => CreatureEffectTag::CureInfection,
    "CE_HEAL_TISSUES" => CreatureEffectTag::HealTissues,
    "CE_HEAL_NERVES" => CreatureEffectTag::HealNerves,
    "CE_REGROW_PARTS" => CreatureEffectTag::RegrowParts,

    "CE_ADD_TAG" => CreatureEffectTag::AddTag,
    "CE_REMOVE_TAG" => CreatureEffectTag::RemoveTag,
    "CE_DISPLAY_NAME" => CreatureEffectTag::DisplayName,
    "CE_DISPLAY_TILE" => CreatureEffectTag::DisplayTile,
    "CE_FLASH_TILE" => CreatureEffectTag::FlashTile,
    "CE_PHYS_ATT_CHANGE" => CreatureEffectTag::PhysAttChange,
    "CE_MENT_ATT_CHANGE" => CreatureEffectTag::MentAttChange,
    "CE_SPEED_CHANGE" => CreatureEffectTag::SpeedChange,
    "CE_SKILL_ROLL_ADJUST" => CreatureEffectTag::SkillRollAdjust,
    "CE_BODY_APPEARANCE_MODIFIER" => CreatureEffectTag::BodyAppearanceModifier,
    "CE_BODYPART_APPEARANCE_MODIFIER" => CreatureEffectTag::BodyPartAppearanceModifier,
    "CE_BODY_TRANSFORMATION" => CreatureEffectTag::BodyTransformation,
    "CE_MATERIAL_FORCE_MULTIPLIER" => CreatureEffectTag::MaterialForceMultiplier,
    "CE_CAN_DO_INTERACTION" => CreatureEffectTag::CanDoInteraction,
    "CE_SPECIAL_ATTACK_INTERACTION" => CreatureEffectTag::SpecialAttackInteraction,
    "CE_BODY_MAT_INTERACTION" => CreatureEffectTag::BodyMatInteraction,
    "CE_SENSE_CREATURE_CLASS" => CreatureEffectTag::SenseCreatureClass,
    "CE_FEEL_EMOTION" => CreatureEffectTag::FeelEmotion,
    "CE_CHANGE_PERSONALITY" => CreatureEffectTag::ChangePersonality,
    "CE_ERRATIC_BEHAVIOR" => CreatureEffectTag::ErraticBehavior,
};
