//! String token to parsed tag map for graphic type tokens.

use crate::tags::GraphicTypeTag;

/// Map of graphic type tags to their string representation.
pub static GRAPHIC_TYPE_TOKENS: phf::Map<&'static str, GraphicTypeTag> = phf::phf_map! {
  "CREATURE_GRAPHICS" => GraphicTypeTag::Creature,
  "CREATURE_CASTE_GRAPHICS" => GraphicTypeTag::CreatureCaste,
  "TILE_GRAPHICS" => GraphicTypeTag::Tile,
  "PLANT_GRAPHICS" => GraphicTypeTag::Plant,

  // "Conditions" which need to point to plant graphics
  "SHRUB" => GraphicTypeTag::Plant,
  "SHRUB_DEAD" => GraphicTypeTag::Plant,
  "PICKED" => GraphicTypeTag::Plant,
  "SEED" => GraphicTypeTag::Plant,
  "SAPLING" => GraphicTypeTag::Plant,
  "CROP" => GraphicTypeTag::Plant,
  "CROP_SPROUT" => GraphicTypeTag::Plant,
  "CROP_L" => GraphicTypeTag::Plant,
  "CROP_M" => GraphicTypeTag::Plant,
  "CROP_R" => GraphicTypeTag::Plant,

  // Interface graphics
  // [CUSTOM_WORKSHOP_GRAPHICS:SCREW_PRESS]
  "CUSTOM_WORKSHOP_GRAPHICS" => GraphicTypeTag::CustomWorkshop,
  // [LIST_ICON:BUILDING_ICONS_TWEAKED:1:12]
  "LIST_ICON" => GraphicTypeTag::ListIcon,

  // Plant Graphics
  // [SOIL_BACKGROUND]
  "SOIL_BACKGROUND" => GraphicTypeTag::SoilBackground,
  // [GRASS_1:GRASS:0:0]
  "GRASS_1" => GraphicTypeTag::Grass1,
  // [GRASS_2:GRASS:1:0]
  "GRASS_2" => GraphicTypeTag::Grass2,
  // [GRASS_3:GRASS:2:0]
  "GRASS_3" => GraphicTypeTag::Grass3,
  // [GRASS_4:GRASS:3:0]
  "GRASS_4" => GraphicTypeTag::Grass4,

  // All other graphic types from the vanilla raws
  // [ADD_TOOL_GRAPHICS:ITEM_TOOL_LARGE_POT]
  "ADD_TOOL_GRAPHICS" => GraphicTypeTag::AddTool,
  // [AMMO_GRAPHICS:ITEM_AMMO_BOLTS]
  "AMMO_GRAPHICS" => GraphicTypeTag::Ammo,
  // [AMMO_GRAPHICS_STRAIGHT_DEFAULT:ITEM_AMMO:1:0]
  "AMMO_GRAPHICS_STRAIGHT_DEFAULT" => GraphicTypeTag::AmmoStraightDefault,
  // [AMMO_GRAPHICS_STRAIGHT_WOOD:ITEM_AMMO:0:0]
  "AMMO_GRAPHICS_STRAIGHT_WOOD" => GraphicTypeTag::AmmoStraightWood,
  // [AMMO_GRAPHICS_DIAGONAL_DEFAULT:ITEM_AMMO:1:1]
  "AMMO_GRAPHICS_DIAGONAL_DEFAULT" => GraphicTypeTag::AmmoDiagonalDefault,
  // [AMMO_GRAPHICS_DIAGONAL_WOOD:ITEM_AMMO:0:1]
  "AMMO_GRAPHICS_DIAGONAL_WOOD" => GraphicTypeTag::AmmoDiagonalWood,
  // [ARMOR_GRAPHICS:ITEMS3:1:15:ITEM_ARMOR_BREASTPLATE]
  "ARMOR_GRAPHICS" => GraphicTypeTag::Armor,
  "FOOD_GRAPHICS" => GraphicTypeTag::Food,
  // [GLOVES_GRAPHICS:ITEMS3:1:21:ITEM_GLOVES_GAUNTLETS]
  "GLOVES_GRAPHICS" => GraphicTypeTag::Gloves,
  // [HELM_GRAPHICS:ITEMS3:2:15:ITEM_HELM_HELM]
  "HELM_GRAPHICS" => GraphicTypeTag::Helm,
  // [PANTS_GRAPHICS:ITEMS3:0:17:ITEM_PANTS_PANTS]
  "PANTS_GRAPHICS" => GraphicTypeTag::Pants,
  // [ROUGH_GEM_GRAPHICS:BOULDERS:0:8:GLASS_GREEN]
  "ROUGH_GEM_GRAPHICS" => GraphicTypeTag::RoughGem,
  // [SHAPE_GRAPHICS_LARGE_GEM:BAGUETTE_CUT_GEM:GEMS:1:0]
  "SHAPE_GRAPHICS_LARGE_GEM" => GraphicTypeTag::ShapeLargeGem,
  // [SHAPE_GRAPHICS_SMALL_GEM:BAGUETTE_CUT_GEM:SMALLGEMS:0:0]
  "SHAPE_GRAPHICS_SMALL_GEM" => GraphicTypeTag::ShapeSmallGem,
  // [SHIELD_GRAPHICS:ITEMS3:3:16:ITEM_SHIELD_SHIELD]
  "SHIELD_GRAPHICS" => GraphicTypeTag::Shield,
  // [SHIELD_GRAPHICS_WOODEN:ITEMS3:3:14:ITEM_SHIELD_SHIELD]
  "SHIELD_GRAPHICS_WOODEN" => GraphicTypeTag::ShieldWooden,
  // [SHOES_GRAPHICS:ITEMS3:3:18:ITEM_SHOES_SHOES]
  "SHOES_GRAPHICS" => GraphicTypeTag::Shoes,
  // [SHOES_GRAPHICS_METAL:ITEMS3:3:22:ITEM_SHOES_BOOTS]
  "SHOES_GRAPHICS_METAL" => GraphicTypeTag::ShoesMetal,
  // [SIEGEAMMO_GRAPHICS:ITEM_SIEGEAMMO_BALLISTA]
  "SIEGEAMMO_GRAPHICS" => GraphicTypeTag::SiegeAmmo,
  // [SIEGEAMMO_GRAPHICS_STRAIGHT_DEFAULT:BALLISTA_ARROW:1:0]
  "SIEGEAMMO_GRAPHICS_STRAIGHT_DEFAULT" => GraphicTypeTag::SiegeAmmoStraightDefault,
  // [SIEGEAMMO_GRAPHICS_STRAIGHT_WOOD:BALLISTA_ARROW:0:0]
  "SIEGEAMMO_GRAPHICS_STRAIGHT_WOOD" => GraphicTypeTag::SiegeAmmoStraightWood,
  // [SIEGEAMMO_GRAPHICS_DIAGONAL_DEFAULT:BALLISTA_ARROW:1:1]
  "SIEGEAMMO_GRAPHICS_DIAGONAL_DEFAULT" => GraphicTypeTag::SiegeAmmoDiagonalDefault,
  // [SIEGEAMMO_GRAPHICS_DIAGONAL_WOOD:BALLISTA_ARROW:0:1]
  "SIEGEAMMO_GRAPHICS_DIAGONAL_WOOD" => GraphicTypeTag::SiegeAmmoDiagonalWood,
  // [TOOL_GRAPHICS:TOOLS:0:0:ITEM_TOOL_CAULDRON]
  "TOOL_GRAPHICS" => GraphicTypeTag::Tool,
  // [TOOL_GRAPHICS_WOOD:1:TOOLS:0:11]
  "TOOL_GRAPHICS_WOOD" => GraphicTypeTag::ToolWood,
  // [TOOL_GRAPHICS_STONE:1:TOOLS:1:11]
  "TOOL_GRAPHICS_STONE" => GraphicTypeTag::ToolStone,
  // [TOOL_GRAPHICS_METAL:1:TOOLS:2:11]
  "TOOL_GRAPHICS_METAL" => GraphicTypeTag::ToolMetal,
  // [TOOL_GRAPHICS_HIVE_BLD:CONTAINERS:0:5]
  "TOOL_GRAPHICS_HIVE_BLD" => GraphicTypeTag::ToolHiveBuilding,
  // [TOOL_GRAPHICS_GLASS:1:ITEM_BOOKCASE:0:3]
  "TOOL_GRAPHICS_GLASS" => GraphicTypeTag::ToolGlass,
  // [TOOL_GRAPHICS_SHAPE:PLATONIC_CUBE:TOOLS:1:29]
  "TOOL_GRAPHICS_SHAPE" => GraphicTypeTag::ToolShape,
  // [TOOL_GRAPHICS_GLASS_VARIANT:3:ITEM_BOOKCASE:9:3]
  "TOOL_GRAPHICS_GLASS_VARIANT" => GraphicTypeTag::ToolGlassVariant,
  // [TOOL_GRAPHICS_METAL_VARIANT:3:ITEM_BOOKCASE:9:2]
  "TOOL_GRAPHICS_METAL_VARIANT" => GraphicTypeTag::ToolMetalVariant,
  // [TOOL_GRAPHICS_STONE_VARIANT:3:ITEM_BOOKCASE:9:1]
  "TOOL_GRAPHICS_STONE_VARIANT" => GraphicTypeTag::ToolStoneVariant,
  // [TOOL_GRAPHICS_WOOD_VARIANT:3:ITEM_BOOKCASE:9:0]
  "TOOL_GRAPHICS_WOOD_VARIANT" => GraphicTypeTag::ToolWoodVariant,
  // [TOOL_GRAPHICS_MUD:ITEM_BOOKCASE:12:3]
  "TOOL_GRAPHICS_MUD" => GraphicTypeTag::ToolMud,
  // [TOOL_GRAPHICS_WATER:ITEM_BOOKCASE:12:2]
  "TOOL_GRAPHICS_WATER" => GraphicTypeTag::ToolWater,
  // [TOOL_GRAPHICS_VOMIT:ITEM_BOOKCASE:12:1]
  "TOOL_GRAPHICS_VOMIT" => GraphicTypeTag::ToolVomit,
  // [TOOL_GRAPHICS_BLOOD:ITEM_BOOKCASE:12:0]
  "TOOL_GRAPHICS_BLOOD" => GraphicTypeTag::ToolBlood,
  // [TOOL_GRAPHICS_DAMAGE:3:ITEM_BOOKCASE:11:0]
  "TOOL_GRAPHICS_DAMAGE" => GraphicTypeTag::ToolDamage,
  // [TOOL_GRAPHICS_BANDS:ITEM_BOOKCASE:11:3]
  "TOOL_GRAPHICS_BANDS" => GraphicTypeTag::ToolBands,
  // [TOOL_GRAPHICS_ENGRAVING:ITEM_BOOKCASE:10:3]
  "TOOL_GRAPHICS_ENGRAVING" => GraphicTypeTag::ToolEngraving,
  // [TOOL_GRAPHICS_STUDS:ITEM_BOOKCASE:10:2]
  "TOOL_GRAPHICS_STUDS" => GraphicTypeTag::ToolStuds,
  // [TOOL_GRAPHICS_RINGS:ITEM_BOOKCASE:10:1]
  "TOOL_GRAPHICS_RINGS" => GraphicTypeTag::ToolRings,
  // [TOOL_GRAPHICS_SPIKES:ITEM_BOOKCASE:10:0]
  "TOOL_GRAPHICS_SPIKES" => GraphicTypeTag::ToolSpikes,
  // [TOY_GRAPHICS:ITEM_TOY:0:4:ITEM_TOY_MINIFORGE:WOOD]
  "TOY_GRAPHICS" => GraphicTypeTag::Toy,
  // [TRAPCOMP_GRAPHICS:ITEM_TRAPCOMP:0:0:ITEM_TRAPCOMP_GIANTAXEBLADE]
  "TRAPCOMP_GRAPHICS" => GraphicTypeTag::TrapComponent,
  // [TRAPCOMP_GRAPHICS_WEAPON_TRAP:TRAPS_WEAPON:3:1]
  "TRAPCOMP_GRAPHICS_WEAPON_TRAP" => GraphicTypeTag::TrapComponentWeaponTrap,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_1T:UPRIGHT_WEAPONS:0:1]
  "TRAPCOMP_GRAPHICS_UPRIGHT_1T" => GraphicTypeTag::TrapComponentUpright1T,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_2T:UPRIGHT_WEAPONS:1:1]
  "TRAPCOMP_GRAPHICS_UPRIGHT_2T" => GraphicTypeTag::TrapComponentUpright2T,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_3T:UPRIGHT_WEAPONS:2:1]
  "TRAPCOMP_GRAPHICS_UPRIGHT_3T" => GraphicTypeTag::TrapComponentUpright3T,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_4T:UPRIGHT_WEAPONS:3:1]
  "TRAPCOMP_GRAPHICS_UPRIGHT_4T" => GraphicTypeTag::TrapComponentUpright4T,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_5T:UPRIGHT_WEAPONS:4:1]
  "TRAPCOMP_GRAPHICS_UPRIGHT_5T" => GraphicTypeTag::TrapComponentUpright5T,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_6T:UPRIGHT_WEAPONS:5:1]
  "TRAPCOMP_GRAPHICS_UPRIGHT_6T" => GraphicTypeTag::TrapComponentUpright6T,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_7T:UPRIGHT_WEAPONS:6:1]
  "TRAPCOMP_GRAPHICS_UPRIGHT_7T" => GraphicTypeTag::TrapComponentUpright7T,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_8T:UPRIGHT_WEAPONS:7:1]
  "TRAPCOMP_GRAPHICS_UPRIGHT_8T" => GraphicTypeTag::TrapComponentUpright8T,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_9T:UPRIGHT_WEAPONS:8:1]
  "TRAPCOMP_GRAPHICS_UPRIGHT_9T" => GraphicTypeTag::TrapComponentUpright9T,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_10T:UPRIGHT_WEAPONS:9:1]
  "TRAPCOMP_GRAPHICS_UPRIGHT_10T" => GraphicTypeTag::TrapComponentUpright10T,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_1B:UPRIGHT_WEAPONS:0:2]
  "TRAPCOMP_GRAPHICS_UPRIGHT_1B" => GraphicTypeTag::TrapComponentUpright1B,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_2B:UPRIGHT_WEAPONS:1:2]
  "TRAPCOMP_GRAPHICS_UPRIGHT_2B" => GraphicTypeTag::TrapComponentUpright2B,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_3B:UPRIGHT_WEAPONS:2:2]
  "TRAPCOMP_GRAPHICS_UPRIGHT_3B" => GraphicTypeTag::TrapComponentUpright3B,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_4B:UPRIGHT_WEAPONS:3:2]
  "TRAPCOMP_GRAPHICS_UPRIGHT_4B" => GraphicTypeTag::TrapComponentUpright4B,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_5B:UPRIGHT_WEAPONS:4:2]
  "TRAPCOMP_GRAPHICS_UPRIGHT_5B" => GraphicTypeTag::TrapComponentUpright5B,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_6B:UPRIGHT_WEAPONS:5:2]
  "TRAPCOMP_GRAPHICS_UPRIGHT_6B" => GraphicTypeTag::TrapComponentUpright6B,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_7B:UPRIGHT_WEAPONS:6:2]
  "TRAPCOMP_GRAPHICS_UPRIGHT_7B" => GraphicTypeTag::TrapComponentUpright7B,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_8B:UPRIGHT_WEAPONS:7:2]
  "TRAPCOMP_GRAPHICS_UPRIGHT_8B" => GraphicTypeTag::TrapComponentUpright8B,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_9B:UPRIGHT_WEAPONS:8:2]
  "TRAPCOMP_GRAPHICS_UPRIGHT_9B" => GraphicTypeTag::TrapComponentUpright9B,
  // [TRAPCOMP_GRAPHICS_UPRIGHT_10B:UPRIGHT_WEAPONS:9:2]
  "TRAPCOMP_GRAPHICS_UPRIGHT_10B" => GraphicTypeTag::TrapComponentUpright10B,
  // [WEAPON_GRAPHICS:ITEM_WEAPON_WHIP]
  "WEAPON_GRAPHICS" => GraphicTypeTag::Weapon,
  // [WEAPON_GRAPHICS_DEFAULT:WEAPONS:0:0]
  "WEAPON_GRAPHICS_DEFAULT" => GraphicTypeTag::WeaponDefault,
  // [WEAPON_GRAPHICS_WOOD:WEAPONS:2:0]
  "WEAPON_GRAPHICS_WOOD" => GraphicTypeTag::WeaponWood,
  // [WEAPON_GRAPHICS_WOOD_GROWN:WEAPONS:1:0]
  "WEAPON_GRAPHICS_WOOD_GROWN" => GraphicTypeTag::WeaponWoodGrown,
  // [WEAPON_GRAPHICS_MATERIAL:WEAPONS:0:0]
  "WEAPON_GRAPHICS_MATERIAL" => GraphicTypeTag::WeaponMaterial,
  // [WEAPON_GRAPHICS_WEAPON_TRAP:TRAPS_WEAPON:7:3]
  "WEAPON_GRAPHICS_WEAPON_TRAP" => GraphicTypeTag::WeaponTrap,
  // [WEAPON_GRAPHICS_UPRIGHT_1T:UPRIGHT_WEAPONS:0:3]
  "WEAPON_GRAPHICS_UPRIGHT_1T" => GraphicTypeTag::WeaponUpright1T,
  // [WEAPON_GRAPHICS_UPRIGHT_2T:UPRIGHT_WEAPONS:1:3]
  "WEAPON_GRAPHICS_UPRIGHT_2T" => GraphicTypeTag::WeaponUpright2T,
  // [WEAPON_GRAPHICS_UPRIGHT_3T:UPRIGHT_WEAPONS:2:3]
  "WEAPON_GRAPHICS_UPRIGHT_3T" => GraphicTypeTag::WeaponUpright3T,
  // [WEAPON_GRAPHICS_UPRIGHT_4T:UPRIGHT_WEAPONS:3:3]
  "WEAPON_GRAPHICS_UPRIGHT_4T" => GraphicTypeTag::WeaponUpright4T,
  // [WEAPON_GRAPHICS_UPRIGHT_5T:UPRIGHT_WEAPONS:4:3]
  "WEAPON_GRAPHICS_UPRIGHT_5T" => GraphicTypeTag::WeaponUpright5T,
  // [WEAPON_GRAPHICS_UPRIGHT_6T:UPRIGHT_WEAPONS:5:3]
  "WEAPON_GRAPHICS_UPRIGHT_6T" => GraphicTypeTag::WeaponUpright6T,
  // [WEAPON_GRAPHICS_UPRIGHT_7T:UPRIGHT_WEAPONS:6:3]
  "WEAPON_GRAPHICS_UPRIGHT_7T" => GraphicTypeTag::WeaponUpright7T,
  // [WEAPON_GRAPHICS_UPRIGHT_8T:UPRIGHT_WEAPONS:7:3]
  "WEAPON_GRAPHICS_UPRIGHT_8T" => GraphicTypeTag::WeaponUpright8T,
  // [WEAPON_GRAPHICS_UPRIGHT_9T:UPRIGHT_WEAPONS:8:3]
  "WEAPON_GRAPHICS_UPRIGHT_9T" => GraphicTypeTag::WeaponUpright9T,
  // [WEAPON_GRAPHICS_UPRIGHT_10T:UPRIGHT_WEAPONS:9:3]
  "WEAPON_GRAPHICS_UPRIGHT_10T" => GraphicTypeTag::WeaponUpright10T,
  // [WEAPON_GRAPHICS_UPRIGHT_1B:UPRIGHT_WEAPONS:0:4]
  "WEAPON_GRAPHICS_UPRIGHT_1B" => GraphicTypeTag::WeaponUpright1B,
  // [WEAPON_GRAPHICS_UPRIGHT_2B:UPRIGHT_WEAPONS:1:4]
  "WEAPON_GRAPHICS_UPRIGHT_2B" => GraphicTypeTag::WeaponUpright2B,
  // [WEAPON_GRAPHICS_UPRIGHT_3B:UPRIGHT_WEAPONS:2:4]
  "WEAPON_GRAPHICS_UPRIGHT_3B" => GraphicTypeTag::WeaponUpright3B,
  // [WEAPON_GRAPHICS_UPRIGHT_4B:UPRIGHT_WEAPONS:3:4]
  "WEAPON_GRAPHICS_UPRIGHT_4B" => GraphicTypeTag::WeaponUpright4B,
  // [WEAPON_GRAPHICS_UPRIGHT_5B:UPRIGHT_WEAPONS:4:4]
  "WEAPON_GRAPHICS_UPRIGHT_5B" => GraphicTypeTag::WeaponUpright5B,
  // [WEAPON_GRAPHICS_UPRIGHT_6B:UPRIGHT_WEAPONS:5:4]
  "WEAPON_GRAPHICS_UPRIGHT_6B" => GraphicTypeTag::WeaponUpright6B,
  // [WEAPON_GRAPHICS_UPRIGHT_7B:UPRIGHT_WEAPONS:6:4]
  "WEAPON_GRAPHICS_UPRIGHT_7B" => GraphicTypeTag::WeaponUpright7B,
  // [WEAPON_GRAPHICS_UPRIGHT_8B:UPRIGHT_WEAPONS:7:4]
  "WEAPON_GRAPHICS_UPRIGHT_8B" => GraphicTypeTag::WeaponUpright8B,
  // [WEAPON_GRAPHICS_UPRIGHT_9B:UPRIGHT_WEAPONS:8:4]
  "WEAPON_GRAPHICS_UPRIGHT_9B" => GraphicTypeTag::WeaponUpright9B,
  // [WEAPON_GRAPHICS_UPRIGHT_10B:UPRIGHT_WEAPONS:9:4]
  "WEAPON_GRAPHICS_UPRIGHT_10B" => GraphicTypeTag::WeaponUpright10B,

  // Creature Graphics
  "STATUE_CREATURE_GRAPHICS" => GraphicTypeTag::StatueCreature,
  "STATUE_CREATURE_CASTE_GRAPHICS" => GraphicTypeTag::StatueCreatureCaste,
  "STATUES_SURFACE_GIANT" => GraphicTypeTag::StatuesSurfaceGiant,

};
