// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityToken } from "./EntityToken";
import type { RawMetadata } from "./RawMetadata";

export interface Entity {
  metadata: RawMetadata;
  identifier: string;
  objectId: string;
  tags: Array<EntityToken>;
  activeSeason: string;
  banditry: number;
  progressTriggerPopulation: number;
  progressTriggerProduction: number;
  progressTriggerTrade: number;
  progressTriggerPopulationSiege: number;
  progressTriggerProductionSiege: number;
  progressTriggerTradeSiege: number;
  scholars: Array<string>;
  ammo: Array<string>;
  armors: Array<[string, number]>;
  diggers: Array<string>;
  gloves: Array<[string, number]>;
  helms: Array<[string, number]>;
  instrument: Array<string>;
  pants: Array<[string, number]>;
  shields: Array<string>;
  shoes: Array<[string, number]>;
  siegeAmmo: Array<string>;
  tool: Array<string>;
  toys: Array<string>;
  trapComponents: Array<string>;
  weapons: Array<string>;
  gemShape: Array<string>;
  stoneShape: Array<string>;
}
