// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphicType } from "./GraphicType";
import type { RawMetadata } from "./RawMetadata";
import type { SpriteGraphic } from "./SpriteGraphic";

export interface Graphic { metadata: RawMetadata, identifier: string, objectId: string, casteIdentifier: string, kind: GraphicType, graphics: Array<SpriteGraphic>, }