// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectType } from "./ObjectType";
import type { RawModuleLocation } from "./RawModuleLocation";

export interface ParserOptions { hideMetadataInResult: boolean, applyCopyTagsFrom: boolean, applyCreatureVariations: boolean, rawsToParse: Array<ObjectType>, locationsToParse: Array<RawModuleLocation>, }