// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlantPart =
  | "Twigs"
  | "Branches"
  | "BranchesAndTwigs"
  | "LightBranches"
  | "LightBranchesAndTwigs"
  | "AllBranchesAndTwigs"
  | "HeavyBranches"
  | "HeavyBranchesAndTrunk"
  | "DirectedBranches"
  | "DirectedBranchesAndTrunk"
  | "Trunk"
  | "Roots"
  | "Cap"
  | "Sapling"
  | "Unknown";
