// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DFColor } from "./DFColor";
import type { SeasonToken } from "./SeasonToken";

export interface Shrub { growingSeason: Array<SeasonToken>, growDuration: number, value: number, pickedTile: number, deadPickedTile: number, shrubTile: number, deadShrubTile: number, clusterSize: number, pickedColor: DFColor, deadPickedColor: DFColor, shrubColor: DFColor, deadShrubColor: DFColor, shrubDrownLevel: number, drink: string, mill: string, thread: string, seed: string, extractStillVial: string, extractVial: string, extractBarrel: string, }